# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.comment import Comment
from ...models.create_comment_body import CreateCommentBody
from ...models.error import Error
from ...types import Response


def _get_kwargs(
    owner: str,
    project: str,
    build_number: str,
    *,
    body: CreateCommentBody,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/projects/{owner}/{project}/builds/{build_number}/comments".format(
            owner=quote(str(owner), safe=""),
            project=quote(str(project), safe=""),
            build_number=quote(str(build_number), safe=""),
        ),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Comment | Error | None:
    if response.status_code == 201:
        response_201 = Comment.from_dict(response.json())

        return response_201

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Comment | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    owner: str,
    project: str,
    build_number: str,
    *,
    client: AuthenticatedClient,
    body: CreateCommentBody,
) -> Response[Comment | Error]:
    """Post a comment (or reply) on a build

     Post a comment on a build. Start a new thread, reply to an existing one with `threadId`, optionally
    anchor the comment to a screenshot diff, or attach it to your pending review with `addToReview`.

    Args:
        owner (str):
        project (str):
        build_number (str): The build number Example: 42.
        body (CreateCommentBody):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Comment | Error]
    """

    kwargs = _get_kwargs(
        owner=owner,
        project=project,
        build_number=build_number,
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    owner: str,
    project: str,
    build_number: str,
    *,
    client: AuthenticatedClient,
    body: CreateCommentBody,
) -> Comment | Error | None:
    """Post a comment (or reply) on a build

     Post a comment on a build. Start a new thread, reply to an existing one with `threadId`, optionally
    anchor the comment to a screenshot diff, or attach it to your pending review with `addToReview`.

    Args:
        owner (str):
        project (str):
        build_number (str): The build number Example: 42.
        body (CreateCommentBody):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Comment | Error
    """

    return sync_detailed(
        owner=owner,
        project=project,
        build_number=build_number,
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    owner: str,
    project: str,
    build_number: str,
    *,
    client: AuthenticatedClient,
    body: CreateCommentBody,
) -> Response[Comment | Error]:
    """Post a comment (or reply) on a build

     Post a comment on a build. Start a new thread, reply to an existing one with `threadId`, optionally
    anchor the comment to a screenshot diff, or attach it to your pending review with `addToReview`.

    Args:
        owner (str):
        project (str):
        build_number (str): The build number Example: 42.
        body (CreateCommentBody):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Comment | Error]
    """

    kwargs = _get_kwargs(
        owner=owner,
        project=project,
        build_number=build_number,
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    owner: str,
    project: str,
    build_number: str,
    *,
    client: AuthenticatedClient,
    body: CreateCommentBody,
) -> Comment | Error | None:
    """Post a comment (or reply) on a build

     Post a comment on a build. Start a new thread, reply to an existing one with `threadId`, optionally
    anchor the comment to a screenshot diff, or attach it to your pending review with `addToReview`.

    Args:
        owner (str):
        project (str):
        build_number (str): The build number Example: 42.
        body (CreateCommentBody):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Comment | Error
    """

    return (
        await asyncio_detailed(
            owner=owner,
            project=project,
            build_number=build_number,
            client=client,
            body=body,
        )
    ).parsed
