# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
"""Contains all the data models used in inputs/outputs"""

from .account import Account
from .account_analytics import AccountAnalytics
from .account_analytics_builds import AccountAnalyticsBuilds
from .account_analytics_builds_all import AccountAnalyticsBuildsAll
from .account_analytics_builds_all_projects import AccountAnalyticsBuildsAllProjects
from .account_analytics_builds_projects_item import AccountAnalyticsBuildsProjectsItem
from .account_analytics_builds_series_item import AccountAnalyticsBuildsSeriesItem
from .account_analytics_builds_series_item_projects import AccountAnalyticsBuildsSeriesItemProjects
from .account_analytics_screenshots import AccountAnalyticsScreenshots
from .account_analytics_screenshots_all import AccountAnalyticsScreenshotsAll
from .account_analytics_screenshots_all_projects import AccountAnalyticsScreenshotsAllProjects
from .account_analytics_screenshots_projects_item import AccountAnalyticsScreenshotsProjectsItem
from .account_analytics_screenshots_series_item import AccountAnalyticsScreenshotsSeriesItem
from .account_analytics_screenshots_series_item_projects import (
    AccountAnalyticsScreenshotsSeriesItemProjects,
)
from .add_comment_reaction_body import AddCommentReactionBody
from .build import Build
from .build_conclusion_type_0 import BuildConclusionType0
from .build_git_reference import BuildGitReference
from .build_metadata import BuildMetadata
from .build_metadata_test_report import BuildMetadataTestReport
from .build_metadata_test_report_stats import BuildMetadataTestReportStats
from .build_metadata_test_report_status import BuildMetadataTestReportStatus
from .build_metadata_type_0 import BuildMetadataType0
from .build_metadata_type_0_test_report import BuildMetadataType0TestReport
from .build_metadata_type_0_test_report_stats import BuildMetadataType0TestReportStats
from .build_metadata_type_0_test_report_status import BuildMetadataType0TestReportStatus
from .build_notification_type_0 import BuildNotificationType0
from .build_notification_type_0_github import BuildNotificationType0Github
from .build_notification_type_0_github_state import BuildNotificationType0GithubState
from .build_notification_type_0_gitlab import BuildNotificationType0Gitlab
from .build_notification_type_0_gitlab_state import BuildNotificationType0GitlabState
from .build_review import BuildReview
from .build_review_state import BuildReviewState
from .build_review_user import BuildReviewUser
from .build_stats_type_0 import BuildStatsType0
from .build_status_type_0 import BuildStatusType0
from .build_status_type_1 import BuildStatusType1
from .build_status_type_2 import BuildStatusType2
from .change import Change
from .comment import Comment
from .comment_anchor_type_0_type_0 import CommentAnchorType0Type0
from .comment_anchor_type_0_type_1 import CommentAnchorType0Type1
from .comment_reactions_item import CommentReactionsItem
from .create_build_body import CreateBuildBody
from .create_build_body_mode_type_0 import CreateBuildBodyModeType0
from .create_build_response_201 import CreateBuildResponse201
from .create_build_response_201_pw_traces_item_type_0 import CreateBuildResponse201PwTracesItemType0
from .create_build_response_201_pw_traces_item_type_1 import CreateBuildResponse201PwTracesItemType1
from .create_build_response_201_pw_traces_item_type_1_fields import (
    CreateBuildResponse201PwTracesItemType1Fields,
)
from .create_build_response_201_screenshots_item_type_0 import (
    CreateBuildResponse201ScreenshotsItemType0,
)
from .create_build_response_201_screenshots_item_type_1 import (
    CreateBuildResponse201ScreenshotsItemType1,
)
from .create_build_response_201_screenshots_item_type_1_fields import (
    CreateBuildResponse201ScreenshotsItemType1Fields,
)
from .create_comment_body import CreateCommentBody
from .create_comment_body_anchor_type_0 import CreateCommentBodyAnchorType0
from .create_comment_body_anchor_type_1 import CreateCommentBodyAnchorType1
from .create_comment_body_body_type_1 import CreateCommentBodyBodyType1
from .create_deployment_body import CreateDeploymentBody
from .create_deployment_body_environment import CreateDeploymentBodyEnvironment
from .create_deployment_body_files_item import CreateDeploymentBodyFilesItem
from .create_deployment_response_201 import CreateDeploymentResponse201
from .create_deployment_response_201_upload_files_item import (
    CreateDeploymentResponse201UploadFilesItem,
)
from .create_project_body import CreateProjectBody
from .create_review_body import CreateReviewBody
from .create_review_body_conclusion import CreateReviewBodyConclusion
from .create_review_body_event import CreateReviewBodyEvent
from .create_review_body_snapshots_item import CreateReviewBodySnapshotsItem
from .create_review_body_snapshots_item_conclusion import CreateReviewBodySnapshotsItemConclusion
from .error import Error
from .error_details_item import ErrorDetailsItem
from .exchange_cli_token_body import ExchangeCliTokenBody
from .exchange_cli_token_response_200 import ExchangeCliTokenResponse200
from .exchange_git_hub_actions_oidc_token_body import ExchangeGitHubActionsOidcTokenBody
from .exchange_git_hub_actions_oidc_token_response_200 import (
    ExchangeGitHubActionsOidcTokenResponse200,
)
from .exchange_git_hub_actions_tokenless_token_body import ExchangeGitHubActionsTokenlessTokenBody
from .exchange_git_hub_actions_tokenless_token_response_200 import (
    ExchangeGitHubActionsTokenlessTokenResponse200,
)
from .finalize_builds_body import FinalizeBuildsBody
from .finalize_builds_response_200 import FinalizeBuildsResponse200
from .finalize_deployment_response_200 import FinalizeDeploymentResponse200
from .finalize_deployment_response_200_environment import FinalizeDeploymentResponse200Environment
from .finalize_deployment_response_200_status import FinalizeDeploymentResponse200Status
from .find_baseline_body import FindBaselineBody
from .find_baseline_body_mode import FindBaselineBodyMode
from .find_baseline_response_200 import FindBaselineResponse200
from .get_account_analytics_group_by import GetAccountAnalyticsGroupBy
from .get_deployment_response_200 import GetDeploymentResponse200
from .get_deployment_response_200_environment import GetDeploymentResponse200Environment
from .get_deployment_response_200_status import GetDeploymentResponse200Status
from .ignore_change_metrics_period import IgnoreChangeMetricsPeriod
from .list_build_diffs_metrics_period import ListBuildDiffsMetricsPeriod
from .list_build_diffs_response_200 import ListBuildDiffsResponse200
from .list_builds_response_200 import ListBuildsResponse200
from .list_projects_response_200 import ListProjectsResponse200
from .me import Me
from .me_account import MeAccount
from .me_account_type import MeAccountType
from .me_github import MeGithub
from .me_user import MeUser
from .page_info import PageInfo
from .pr_context_changed_file import PrContextChangedFile
from .pr_context_type_0 import PrContextType0
from .project import Project
from .resolve_deployment_domain_response_200 import ResolveDeploymentDomainResponse200
from .resolve_deployment_domain_response_200_environment import (
    ResolveDeploymentDomainResponse200Environment,
)
from .resolve_deployment_domain_response_200_visibility import (
    ResolveDeploymentDomainResponse200Visibility,
)
from .screenshot_input import ScreenshotInput
from .screenshot_input_metadata_type_0 import ScreenshotInputMetadataType0
from .screenshot_input_metadata_type_0_automation_library import (
    ScreenshotInputMetadataType0AutomationLibrary,
)
from .screenshot_input_metadata_type_0_browser_type_0 import (
    ScreenshotInputMetadataType0BrowserType0,
)
from .screenshot_input_metadata_type_0_color_scheme_type_0 import (
    ScreenshotInputMetadataType0ColorSchemeType0,
)
from .screenshot_input_metadata_type_0_media_type_type_0 import (
    ScreenshotInputMetadataType0MediaTypeType0,
)
from .screenshot_input_metadata_type_0_sdk import ScreenshotInputMetadataType0Sdk
from .screenshot_input_metadata_type_0_story_type_0 import ScreenshotInputMetadataType0StoryType0
from .screenshot_input_metadata_type_0_test_type_0 import ScreenshotInputMetadataType0TestType0
from .screenshot_input_metadata_type_0_test_type_0_annotations_item import (
    ScreenshotInputMetadataType0TestType0AnnotationsItem,
)
from .screenshot_input_metadata_type_0_test_type_0_annotations_item_location import (
    ScreenshotInputMetadataType0TestType0AnnotationsItemLocation,
)
from .screenshot_input_metadata_type_0_test_type_0_location import (
    ScreenshotInputMetadataType0TestType0Location,
)
from .screenshot_input_metadata_type_0_viewport_type_0 import (
    ScreenshotInputMetadataType0ViewportType0,
)
from .screenshot_upload_request import ScreenshotUploadRequest
from .snapshot_diff import SnapshotDiff
from .snapshot_diff_base_type_0 import SnapshotDiffBaseType0
from .snapshot_diff_base_type_0_metadata_type_0 import SnapshotDiffBaseType0MetadataType0
from .snapshot_diff_base_type_0_metadata_type_0_automation_library import (
    SnapshotDiffBaseType0MetadataType0AutomationLibrary,
)
from .snapshot_diff_base_type_0_metadata_type_0_browser_type_0 import (
    SnapshotDiffBaseType0MetadataType0BrowserType0,
)
from .snapshot_diff_base_type_0_metadata_type_0_color_scheme_type_0 import (
    SnapshotDiffBaseType0MetadataType0ColorSchemeType0,
)
from .snapshot_diff_base_type_0_metadata_type_0_media_type_type_0 import (
    SnapshotDiffBaseType0MetadataType0MediaTypeType0,
)
from .snapshot_diff_base_type_0_metadata_type_0_sdk import SnapshotDiffBaseType0MetadataType0Sdk
from .snapshot_diff_base_type_0_metadata_type_0_story_type_0 import (
    SnapshotDiffBaseType0MetadataType0StoryType0,
)
from .snapshot_diff_base_type_0_metadata_type_0_test_type_0 import (
    SnapshotDiffBaseType0MetadataType0TestType0,
)
from .snapshot_diff_base_type_0_metadata_type_0_test_type_0_annotations_item import (
    SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem,
)
from .snapshot_diff_base_type_0_metadata_type_0_test_type_0_annotations_item_location import (
    SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItemLocation,
)
from .snapshot_diff_base_type_0_metadata_type_0_test_type_0_location import (
    SnapshotDiffBaseType0MetadataType0TestType0Location,
)
from .snapshot_diff_base_type_0_metadata_type_0_viewport_type_0 import (
    SnapshotDiffBaseType0MetadataType0ViewportType0,
)
from .snapshot_diff_change_type_0 import SnapshotDiffChangeType0
from .snapshot_diff_head_type_0 import SnapshotDiffHeadType0
from .snapshot_diff_head_type_0_metadata_type_0 import SnapshotDiffHeadType0MetadataType0
from .snapshot_diff_head_type_0_metadata_type_0_automation_library import (
    SnapshotDiffHeadType0MetadataType0AutomationLibrary,
)
from .snapshot_diff_head_type_0_metadata_type_0_browser_type_0 import (
    SnapshotDiffHeadType0MetadataType0BrowserType0,
)
from .snapshot_diff_head_type_0_metadata_type_0_color_scheme_type_0 import (
    SnapshotDiffHeadType0MetadataType0ColorSchemeType0,
)
from .snapshot_diff_head_type_0_metadata_type_0_media_type_type_0 import (
    SnapshotDiffHeadType0MetadataType0MediaTypeType0,
)
from .snapshot_diff_head_type_0_metadata_type_0_sdk import SnapshotDiffHeadType0MetadataType0Sdk
from .snapshot_diff_head_type_0_metadata_type_0_story_type_0 import (
    SnapshotDiffHeadType0MetadataType0StoryType0,
)
from .snapshot_diff_head_type_0_metadata_type_0_test_type_0 import (
    SnapshotDiffHeadType0MetadataType0TestType0,
)
from .snapshot_diff_head_type_0_metadata_type_0_test_type_0_annotations_item import (
    SnapshotDiffHeadType0MetadataType0TestType0AnnotationsItem,
)
from .snapshot_diff_head_type_0_metadata_type_0_test_type_0_annotations_item_location import (
    SnapshotDiffHeadType0MetadataType0TestType0AnnotationsItemLocation,
)
from .snapshot_diff_head_type_0_metadata_type_0_test_type_0_location import (
    SnapshotDiffHeadType0MetadataType0TestType0Location,
)
from .snapshot_diff_head_type_0_metadata_type_0_viewport_type_0 import (
    SnapshotDiffHeadType0MetadataType0ViewportType0,
)
from .snapshot_diff_status import SnapshotDiffStatus
from .test import Test
from .test_metrics import TestMetrics
from .unignore_change_metrics_period import UnignoreChangeMetricsPeriod
from .update_build_body import UpdateBuildBody
from .update_build_response_200 import UpdateBuildResponse200
from .update_comment_body import UpdateCommentBody
from .update_comment_body_body_type_1 import UpdateCommentBodyBodyType1
from .user import User

__all__ = (
    "Account",
    "AccountAnalytics",
    "AccountAnalyticsBuilds",
    "AccountAnalyticsBuildsAll",
    "AccountAnalyticsBuildsAllProjects",
    "AccountAnalyticsBuildsProjectsItem",
    "AccountAnalyticsBuildsSeriesItem",
    "AccountAnalyticsBuildsSeriesItemProjects",
    "AccountAnalyticsScreenshots",
    "AccountAnalyticsScreenshotsAll",
    "AccountAnalyticsScreenshotsAllProjects",
    "AccountAnalyticsScreenshotsProjectsItem",
    "AccountAnalyticsScreenshotsSeriesItem",
    "AccountAnalyticsScreenshotsSeriesItemProjects",
    "AddCommentReactionBody",
    "Build",
    "BuildConclusionType0",
    "BuildGitReference",
    "BuildMetadata",
    "BuildMetadataTestReport",
    "BuildMetadataTestReportStats",
    "BuildMetadataTestReportStatus",
    "BuildMetadataType0",
    "BuildMetadataType0TestReport",
    "BuildMetadataType0TestReportStats",
    "BuildMetadataType0TestReportStatus",
    "BuildNotificationType0",
    "BuildNotificationType0Github",
    "BuildNotificationType0GithubState",
    "BuildNotificationType0Gitlab",
    "BuildNotificationType0GitlabState",
    "BuildReview",
    "BuildReviewState",
    "BuildReviewUser",
    "BuildStatsType0",
    "BuildStatusType0",
    "BuildStatusType1",
    "BuildStatusType2",
    "Change",
    "Comment",
    "CommentAnchorType0Type0",
    "CommentAnchorType0Type1",
    "CommentReactionsItem",
    "CreateBuildBody",
    "CreateBuildBodyModeType0",
    "CreateBuildResponse201",
    "CreateBuildResponse201PwTracesItemType0",
    "CreateBuildResponse201PwTracesItemType1",
    "CreateBuildResponse201PwTracesItemType1Fields",
    "CreateBuildResponse201ScreenshotsItemType0",
    "CreateBuildResponse201ScreenshotsItemType1",
    "CreateBuildResponse201ScreenshotsItemType1Fields",
    "CreateCommentBody",
    "CreateCommentBodyAnchorType0",
    "CreateCommentBodyAnchorType1",
    "CreateCommentBodyBodyType1",
    "CreateDeploymentBody",
    "CreateDeploymentBodyEnvironment",
    "CreateDeploymentBodyFilesItem",
    "CreateDeploymentResponse201",
    "CreateDeploymentResponse201UploadFilesItem",
    "CreateProjectBody",
    "CreateReviewBody",
    "CreateReviewBodyConclusion",
    "CreateReviewBodyEvent",
    "CreateReviewBodySnapshotsItem",
    "CreateReviewBodySnapshotsItemConclusion",
    "Error",
    "ErrorDetailsItem",
    "ExchangeCliTokenBody",
    "ExchangeCliTokenResponse200",
    "ExchangeGitHubActionsOidcTokenBody",
    "ExchangeGitHubActionsOidcTokenResponse200",
    "ExchangeGitHubActionsTokenlessTokenBody",
    "ExchangeGitHubActionsTokenlessTokenResponse200",
    "FinalizeBuildsBody",
    "FinalizeBuildsResponse200",
    "FinalizeDeploymentResponse200",
    "FinalizeDeploymentResponse200Environment",
    "FinalizeDeploymentResponse200Status",
    "FindBaselineBody",
    "FindBaselineBodyMode",
    "FindBaselineResponse200",
    "GetAccountAnalyticsGroupBy",
    "GetDeploymentResponse200",
    "GetDeploymentResponse200Environment",
    "GetDeploymentResponse200Status",
    "IgnoreChangeMetricsPeriod",
    "ListBuildDiffsMetricsPeriod",
    "ListBuildDiffsResponse200",
    "ListBuildsResponse200",
    "ListProjectsResponse200",
    "Me",
    "MeAccount",
    "MeAccountType",
    "MeGithub",
    "MeUser",
    "PageInfo",
    "PrContextChangedFile",
    "PrContextType0",
    "Project",
    "ResolveDeploymentDomainResponse200",
    "ResolveDeploymentDomainResponse200Environment",
    "ResolveDeploymentDomainResponse200Visibility",
    "ScreenshotInput",
    "ScreenshotInputMetadataType0",
    "ScreenshotInputMetadataType0AutomationLibrary",
    "ScreenshotInputMetadataType0BrowserType0",
    "ScreenshotInputMetadataType0ColorSchemeType0",
    "ScreenshotInputMetadataType0MediaTypeType0",
    "ScreenshotInputMetadataType0Sdk",
    "ScreenshotInputMetadataType0StoryType0",
    "ScreenshotInputMetadataType0TestType0",
    "ScreenshotInputMetadataType0TestType0AnnotationsItem",
    "ScreenshotInputMetadataType0TestType0AnnotationsItemLocation",
    "ScreenshotInputMetadataType0TestType0Location",
    "ScreenshotInputMetadataType0ViewportType0",
    "ScreenshotUploadRequest",
    "SnapshotDiff",
    "SnapshotDiffBaseType0",
    "SnapshotDiffBaseType0MetadataType0",
    "SnapshotDiffBaseType0MetadataType0AutomationLibrary",
    "SnapshotDiffBaseType0MetadataType0BrowserType0",
    "SnapshotDiffBaseType0MetadataType0ColorSchemeType0",
    "SnapshotDiffBaseType0MetadataType0MediaTypeType0",
    "SnapshotDiffBaseType0MetadataType0Sdk",
    "SnapshotDiffBaseType0MetadataType0StoryType0",
    "SnapshotDiffBaseType0MetadataType0TestType0",
    "SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem",
    "SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItemLocation",
    "SnapshotDiffBaseType0MetadataType0TestType0Location",
    "SnapshotDiffBaseType0MetadataType0ViewportType0",
    "SnapshotDiffChangeType0",
    "SnapshotDiffHeadType0",
    "SnapshotDiffHeadType0MetadataType0",
    "SnapshotDiffHeadType0MetadataType0AutomationLibrary",
    "SnapshotDiffHeadType0MetadataType0BrowserType0",
    "SnapshotDiffHeadType0MetadataType0ColorSchemeType0",
    "SnapshotDiffHeadType0MetadataType0MediaTypeType0",
    "SnapshotDiffHeadType0MetadataType0Sdk",
    "SnapshotDiffHeadType0MetadataType0StoryType0",
    "SnapshotDiffHeadType0MetadataType0TestType0",
    "SnapshotDiffHeadType0MetadataType0TestType0AnnotationsItem",
    "SnapshotDiffHeadType0MetadataType0TestType0AnnotationsItemLocation",
    "SnapshotDiffHeadType0MetadataType0TestType0Location",
    "SnapshotDiffHeadType0MetadataType0ViewportType0",
    "SnapshotDiffStatus",
    "Test",
    "TestMetrics",
    "UnignoreChangeMetricsPeriod",
    "UpdateBuildBody",
    "UpdateBuildResponse200",
    "UpdateCommentBody",
    "UpdateCommentBodyBodyType1",
    "User",
)
