# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.account_analytics_screenshots_all_projects import (
        AccountAnalyticsScreenshotsAllProjects,
    )


T = TypeVar("T", bound="AccountAnalyticsScreenshotsAll")


@_attrs_define
class AccountAnalyticsScreenshotsAll:
    """
    Attributes:
        total (int):
        projects (AccountAnalyticsScreenshotsAllProjects): Counts keyed by project ID. Use the sibling `projects` array
            to resolve each project name.
    """

    total: int
    projects: AccountAnalyticsScreenshotsAllProjects

    def to_dict(self) -> dict[str, Any]:
        total = self.total

        projects = self.projects.to_dict()

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "total": total,
                "projects": projects,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.account_analytics_screenshots_all_projects import (
            AccountAnalyticsScreenshotsAllProjects,
        )

        d = dict(src_dict)
        total = d.pop("total")

        projects = AccountAnalyticsScreenshotsAllProjects.from_dict(d.pop("projects"))

        account_analytics_screenshots_all = cls(
            total=total,
            projects=projects,
        )

        return account_analytics_screenshots_all
