# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.account_analytics_screenshots_series_item_projects import (
        AccountAnalyticsScreenshotsSeriesItemProjects,
    )


T = TypeVar("T", bound="AccountAnalyticsScreenshotsSeriesItem")


@_attrs_define
class AccountAnalyticsScreenshotsSeriesItem:
    """
    Attributes:
        total (int):
        projects (AccountAnalyticsScreenshotsSeriesItemProjects): Counts keyed by project ID. Use the sibling `projects`
            array to resolve each project name.
        ts (int): Unix timestamp in milliseconds at the start of the period.
    """

    total: int
    projects: AccountAnalyticsScreenshotsSeriesItemProjects
    ts: int

    def to_dict(self) -> dict[str, Any]:
        total = self.total

        projects = self.projects.to_dict()

        ts = self.ts

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "total": total,
                "projects": projects,
                "ts": ts,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.account_analytics_screenshots_series_item_projects import (
            AccountAnalyticsScreenshotsSeriesItemProjects,
        )

        d = dict(src_dict)
        total = d.pop("total")

        projects = AccountAnalyticsScreenshotsSeriesItemProjects.from_dict(d.pop("projects"))

        ts = d.pop("ts")

        account_analytics_screenshots_series_item = cls(
            total=total,
            projects=projects,
            ts=ts,
        )

        return account_analytics_screenshots_series_item
