# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.account_analytics_builds_all_projects import AccountAnalyticsBuildsAllProjects


T = TypeVar("T", bound="AccountAnalyticsBuildsAll")


@_attrs_define
class AccountAnalyticsBuildsAll:
    """
    Attributes:
        total (int):
        projects (AccountAnalyticsBuildsAllProjects): Counts keyed by project ID. Use the sibling `projects` array to
            resolve each project name.
        changes_detected (int):
        no_changes (int):
        accepted (int):
        rejected (int):
    """

    total: int
    projects: AccountAnalyticsBuildsAllProjects
    changes_detected: int
    no_changes: int
    accepted: int
    rejected: int

    def to_dict(self) -> dict[str, Any]:

        total = self.total

        projects = self.projects.to_dict()

        changes_detected = self.changes_detected

        no_changes = self.no_changes

        accepted = self.accepted

        rejected = self.rejected

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "total": total,
                "projects": projects,
                "changesDetected": changes_detected,
                "noChanges": no_changes,
                "accepted": accepted,
                "rejected": rejected,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.account_analytics_builds_all_projects import AccountAnalyticsBuildsAllProjects

        d = dict(src_dict)
        total = d.pop("total")

        projects = AccountAnalyticsBuildsAllProjects.from_dict(d.pop("projects"))

        changes_detected = d.pop("changesDetected")

        no_changes = d.pop("noChanges")

        accepted = d.pop("accepted")

        rejected = d.pop("rejected")

        account_analytics_builds_all = cls(
            total=total,
            projects=projects,
            changes_detected=changes_detected,
            no_changes=no_changes,
            accepted=accepted,
            rejected=rejected,
        )

        return account_analytics_builds_all
