# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.account_analytics_builds_all import AccountAnalyticsBuildsAll
    from ..models.account_analytics_builds_projects_item import AccountAnalyticsBuildsProjectsItem
    from ..models.account_analytics_builds_series_item import AccountAnalyticsBuildsSeriesItem


T = TypeVar("T", bound="AccountAnalyticsBuilds")


@_attrs_define
class AccountAnalyticsBuilds:
    """
    Attributes:
        series (list[AccountAnalyticsBuildsSeriesItem]):
        all_ (AccountAnalyticsBuildsAll):
        projects (list[AccountAnalyticsBuildsProjectsItem]):
    """

    series: list[AccountAnalyticsBuildsSeriesItem]
    all_: AccountAnalyticsBuildsAll
    projects: list[AccountAnalyticsBuildsProjectsItem]

    def to_dict(self) -> dict[str, Any]:
        series = []
        for series_item_data in self.series:
            series_item = series_item_data.to_dict()
            series.append(series_item)

        all_ = self.all_.to_dict()

        projects = []
        for projects_item_data in self.projects:
            projects_item = projects_item_data.to_dict()
            projects.append(projects_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "series": series,
                "all": all_,
                "projects": projects,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.account_analytics_builds_all import AccountAnalyticsBuildsAll
        from ..models.account_analytics_builds_projects_item import (
            AccountAnalyticsBuildsProjectsItem,
        )
        from ..models.account_analytics_builds_series_item import AccountAnalyticsBuildsSeriesItem

        d = dict(src_dict)
        series = []
        _series = d.pop("series")
        for series_item_data in _series:
            series_item = AccountAnalyticsBuildsSeriesItem.from_dict(series_item_data)

            series.append(series_item)

        all_ = AccountAnalyticsBuildsAll.from_dict(d.pop("all"))

        projects = []
        _projects = d.pop("projects")
        for projects_item_data in _projects:
            projects_item = AccountAnalyticsBuildsProjectsItem.from_dict(projects_item_data)

            projects.append(projects_item)

        account_analytics_builds = cls(
            series=series,
            all_=all_,
            projects=projects,
        )

        return account_analytics_builds
