# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.account_analytics_screenshots_all import AccountAnalyticsScreenshotsAll
    from ..models.account_analytics_screenshots_projects_item import (
        AccountAnalyticsScreenshotsProjectsItem,
    )
    from ..models.account_analytics_screenshots_series_item import (
        AccountAnalyticsScreenshotsSeriesItem,
    )


T = TypeVar("T", bound="AccountAnalyticsScreenshots")


@_attrs_define
class AccountAnalyticsScreenshots:
    """
    Attributes:
        series (list[AccountAnalyticsScreenshotsSeriesItem]):
        all_ (AccountAnalyticsScreenshotsAll):
        projects (list[AccountAnalyticsScreenshotsProjectsItem]):
    """

    series: list[AccountAnalyticsScreenshotsSeriesItem]
    all_: AccountAnalyticsScreenshotsAll
    projects: list[AccountAnalyticsScreenshotsProjectsItem]

    def to_dict(self) -> dict[str, Any]:
        series = []
        for series_item_data in self.series:
            series_item = series_item_data.to_dict()
            series.append(series_item)

        all_ = self.all_.to_dict()

        projects = []
        for projects_item_data in self.projects:
            projects_item = projects_item_data.to_dict()
            projects.append(projects_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "series": series,
                "all": all_,
                "projects": projects,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.account_analytics_screenshots_all import AccountAnalyticsScreenshotsAll
        from ..models.account_analytics_screenshots_projects_item import (
            AccountAnalyticsScreenshotsProjectsItem,
        )
        from ..models.account_analytics_screenshots_series_item import (
            AccountAnalyticsScreenshotsSeriesItem,
        )

        d = dict(src_dict)
        series = []
        _series = d.pop("series")
        for series_item_data in _series:
            series_item = AccountAnalyticsScreenshotsSeriesItem.from_dict(series_item_data)

            series.append(series_item)

        all_ = AccountAnalyticsScreenshotsAll.from_dict(d.pop("all"))

        projects = []
        _projects = d.pop("projects")
        for projects_item_data in _projects:
            projects_item = AccountAnalyticsScreenshotsProjectsItem.from_dict(projects_item_data)

            projects.append(projects_item)

        account_analytics_screenshots = cls(
            series=series,
            all_=all_,
            projects=projects,
        )

        return account_analytics_screenshots
