# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.account_analytics_builds_series_item_projects import (
        AccountAnalyticsBuildsSeriesItemProjects,
    )


T = TypeVar("T", bound="AccountAnalyticsBuildsSeriesItem")


@_attrs_define
class AccountAnalyticsBuildsSeriesItem:
    """
    Attributes:
        total (int):
        projects (AccountAnalyticsBuildsSeriesItemProjects): Counts keyed by project ID. Use the sibling `projects`
            array to resolve each project name.
        changes_detected (int):
        no_changes (int):
        accepted (int):
        rejected (int):
        ts (int): Unix timestamp in milliseconds at the start of the period.
    """

    total: int
    projects: AccountAnalyticsBuildsSeriesItemProjects
    changes_detected: int
    no_changes: int
    accepted: int
    rejected: int
    ts: int

    def to_dict(self) -> dict[str, Any]:
        total = self.total

        projects = self.projects.to_dict()

        changes_detected = self.changes_detected

        no_changes = self.no_changes

        accepted = self.accepted

        rejected = self.rejected

        ts = self.ts

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "total": total,
                "projects": projects,
                "changesDetected": changes_detected,
                "noChanges": no_changes,
                "accepted": accepted,
                "rejected": rejected,
                "ts": ts,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.account_analytics_builds_series_item_projects import (
            AccountAnalyticsBuildsSeriesItemProjects,
        )

        d = dict(src_dict)
        total = d.pop("total")

        projects = AccountAnalyticsBuildsSeriesItemProjects.from_dict(d.pop("projects"))

        changes_detected = d.pop("changesDetected")

        no_changes = d.pop("noChanges")

        accepted = d.pop("accepted")

        rejected = d.pop("rejected")

        ts = d.pop("ts")

        account_analytics_builds_series_item = cls(
            total=total,
            projects=projects,
            changes_detected=changes_detected,
            no_changes=no_changes,
            accepted=accepted,
            rejected=rejected,
            ts=ts,
        )

        return account_analytics_builds_series_item
