# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.account_analytics_builds import AccountAnalyticsBuilds
    from ..models.account_analytics_screenshots import AccountAnalyticsScreenshots


T = TypeVar("T", bound="AccountAnalytics")


@_attrs_define
class AccountAnalytics:
    """
    Attributes:
        screenshots (AccountAnalyticsScreenshots):
        builds (AccountAnalyticsBuilds):
    """

    screenshots: AccountAnalyticsScreenshots
    builds: AccountAnalyticsBuilds

    def to_dict(self) -> dict[str, Any]:
        screenshots = self.screenshots.to_dict()

        builds = self.builds.to_dict()

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "screenshots": screenshots,
                "builds": builds,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.account_analytics_builds import AccountAnalyticsBuilds
        from ..models.account_analytics_screenshots import AccountAnalyticsScreenshots

        d = dict(src_dict)
        screenshots = AccountAnalyticsScreenshots.from_dict(d.pop("screenshots"))

        builds = AccountAnalyticsBuilds.from_dict(d.pop("builds"))

        account_analytics = cls(
            screenshots=screenshots,
            builds=builds,
        )

        return account_analytics
