# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from enum import Enum


class BuildStatusType1(str, Enum):
    CHANGES_DETECTED = "changes-detected"
    NO_CHANGES = "no-changes"

    def __str__(self) -> str:
        return str(self.value)
