# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

from ..models.build_notification_type_0_gitlab_state import BuildNotificationType0GitlabState

T = TypeVar("T", bound="BuildNotificationType0Gitlab")


@_attrs_define
class BuildNotificationType0Gitlab:
    """
    Attributes:
        state (BuildNotificationType0GitlabState):
    """

    state: BuildNotificationType0GitlabState

    def to_dict(self) -> dict[str, Any]:
        state = self.state.value

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "state": state,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        state = BuildNotificationType0GitlabState(d.pop("state"))

        build_notification_type_0_gitlab = cls(
            state=state,
        )

        return build_notification_type_0_gitlab
