# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.build_notification_type_0_github import BuildNotificationType0Github
    from ..models.build_notification_type_0_gitlab import BuildNotificationType0Gitlab


T = TypeVar("T", bound="BuildNotificationType0")


@_attrs_define
class BuildNotificationType0:
    """
    Attributes:
        description (str):
        context (str):
        github (BuildNotificationType0Github):
        gitlab (BuildNotificationType0Gitlab):
        url (str):
    """

    description: str
    context: str
    github: BuildNotificationType0Github
    gitlab: BuildNotificationType0Gitlab
    url: str

    def to_dict(self) -> dict[str, Any]:

        description = self.description

        context = self.context

        github = self.github.to_dict()

        gitlab = self.gitlab.to_dict()

        url = self.url

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "description": description,
                "context": context,
                "github": github,
                "gitlab": gitlab,
                "url": url,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build_notification_type_0_github import BuildNotificationType0Github
        from ..models.build_notification_type_0_gitlab import BuildNotificationType0Gitlab

        d = dict(src_dict)
        description = d.pop("description")

        context = d.pop("context")

        github = BuildNotificationType0Github.from_dict(d.pop("github"))

        gitlab = BuildNotificationType0Gitlab.from_dict(d.pop("gitlab"))

        url = d.pop("url")

        build_notification_type_0 = cls(
            description=description,
            context=context,
            github=github,
            gitlab=gitlab,
            url=url,
        )

        return build_notification_type_0
