# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="BuildGitReference")


@_attrs_define
class BuildGitReference:
    """Git reference

    Attributes:
        sha (str): SHA1 hash
        branch (str): The branch name
    """

    sha: str
    branch: str

    def to_dict(self) -> dict[str, Any]:
        sha = self.sha

        branch = self.branch

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "sha": sha,
                "branch": branch,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        sha = d.pop("sha")

        branch = d.pop("branch")

        build_git_reference = cls(
            sha=sha,
            branch=branch,
        )

        return build_git_reference
