# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="BuildStatsType0")


@_attrs_define
class BuildStatsType0:
    """
    Attributes:
        added (float): Added snapshots
        removed (float): Removed snapshots
        unchanged (float): Unchanged snapshots
        changed (float): Changed snapshots
        ignored (float): Ignored snapshots
        failure (float): Failure screenshots
        retry_failure (float): Retry failure screenshots
        total (float): Total number of snapshots
    """

    added: float
    removed: float
    unchanged: float
    changed: float
    ignored: float
    failure: float
    retry_failure: float
    total: float

    def to_dict(self) -> dict[str, Any]:
        added = self.added

        removed = self.removed

        unchanged = self.unchanged

        changed = self.changed

        ignored = self.ignored

        failure = self.failure

        retry_failure = self.retry_failure

        total = self.total

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "added": added,
                "removed": removed,
                "unchanged": unchanged,
                "changed": changed,
                "ignored": ignored,
                "failure": failure,
                "retryFailure": retry_failure,
                "total": total,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        added = d.pop("added")

        removed = d.pop("removed")

        unchanged = d.pop("unchanged")

        changed = d.pop("changed")

        ignored = d.pop("ignored")

        failure = d.pop("failure")

        retry_failure = d.pop("retryFailure")

        total = d.pop("total")

        build_stats_type_0 = cls(
            added=added,
            removed=removed,
            unchanged=unchanged,
            changed=changed,
            ignored=ignored,
            failure=failure,
            retry_failure=retry_failure,
            total=total,
        )

        return build_stats_type_0
