# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.build_metadata_test_report import BuildMetadataTestReport


T = TypeVar("T", bound="BuildMetadata")


@_attrs_define
class BuildMetadata:
    """Build metadata

    Attributes:
        test_report (BuildMetadataTestReport | Unset): Test suite report
    """

    test_report: BuildMetadataTestReport | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:

        test_report: dict[str, Any] | Unset = UNSET
        if not isinstance(self.test_report, Unset):
            test_report = self.test_report.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if test_report is not UNSET:
            field_dict["testReport"] = test_report

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build_metadata_test_report import BuildMetadataTestReport

        d = dict(src_dict)
        _test_report = d.pop("testReport", UNSET)
        test_report: BuildMetadataTestReport | Unset
        if isinstance(_test_report, Unset):
            test_report = UNSET
        else:
            test_report = BuildMetadataTestReport.from_dict(_test_report)

        build_metadata = cls(
            test_report=test_report,
        )

        build_metadata.additional_properties = d
        return build_metadata

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
