# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

from ..types import UNSET, Unset

T = TypeVar("T", bound="BuildMetadataType0TestReportStats")


@_attrs_define
class BuildMetadataType0TestReportStats:
    """
    Attributes:
        start_time (str | Unset): Date when the test suite started
        duration (float | Unset): Duration of the test suite in milliseconds
    """

    start_time: str | Unset = UNSET
    duration: float | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        start_time = self.start_time

        duration = self.duration

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if start_time is not UNSET:
            field_dict["startTime"] = start_time
        if duration is not UNSET:
            field_dict["duration"] = duration

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        start_time = d.pop("startTime", UNSET)

        duration = d.pop("duration", UNSET)

        build_metadata_type_0_test_report_stats = cls(
            start_time=start_time,
            duration=duration,
        )

        return build_metadata_type_0_test_report_stats
