# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.build_metadata_test_report_status import BuildMetadataTestReportStatus
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.build_metadata_test_report_stats import BuildMetadataTestReportStats


T = TypeVar("T", bound="BuildMetadataTestReport")


@_attrs_define
class BuildMetadataTestReport:
    """Test suite report

    Attributes:
        status (BuildMetadataTestReportStatus): Status of the test suite
        stats (BuildMetadataTestReportStats | Unset):
    """

    status: BuildMetadataTestReportStatus
    stats: BuildMetadataTestReportStats | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        status = self.status.value

        stats: dict[str, Any] | Unset = UNSET
        if not isinstance(self.stats, Unset):
            stats = self.stats.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "status": status,
            }
        )
        if stats is not UNSET:
            field_dict["stats"] = stats

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build_metadata_test_report_stats import BuildMetadataTestReportStats

        d = dict(src_dict)
        status = BuildMetadataTestReportStatus(d.pop("status"))

        _stats = d.pop("stats", UNSET)
        stats: BuildMetadataTestReportStats | Unset
        if isinstance(_stats, Unset):
            stats = UNSET
        else:
            stats = BuildMetadataTestReportStats.from_dict(_stats)

        build_metadata_test_report = cls(
            status=status,
            stats=stats,
        )

        build_metadata_test_report.additional_properties = d
        return build_metadata_test_report

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
