# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

from ..models.build_conclusion_type_0 import BuildConclusionType0
from ..models.build_status_type_0 import BuildStatusType0
from ..models.build_status_type_1 import BuildStatusType1
from ..models.build_status_type_2 import BuildStatusType2

if TYPE_CHECKING:
    from ..models.build_git_reference import BuildGitReference
    from ..models.build_metadata_type_0 import BuildMetadataType0
    from ..models.build_notification_type_0 import BuildNotificationType0
    from ..models.build_stats_type_0 import BuildStatsType0


T = TypeVar("T", bound="Build")


@_attrs_define
class Build:
    """Build

    Attributes:
        id (str): A unique identifier for the build Example: 12345.
        number (int): The build number Example: 42.
        head (BuildGitReference): Git reference
        base (BuildGitReference | None): The base reference of the build
        status (BuildStatusType0 | BuildStatusType1 | BuildStatusType2): The status of the build
        conclusion (BuildConclusionType0 | None): The conclusion of the build
        stats (BuildStatsType0 | None): Stats of the diffs present in the build
        metadata (BuildMetadataType0 | None):
        url (str): The URL of the build
        notification (BuildNotificationType0 | None): The notification payload for the build
    """

    id: str
    number: int
    head: BuildGitReference
    base: BuildGitReference | None
    status: BuildStatusType0 | BuildStatusType1 | BuildStatusType2
    conclusion: BuildConclusionType0 | None
    stats: BuildStatsType0 | None
    metadata: BuildMetadataType0 | None
    url: str
    notification: BuildNotificationType0 | None

    def to_dict(self) -> dict[str, Any]:
        from ..models.build_git_reference import BuildGitReference
        from ..models.build_metadata_type_0 import BuildMetadataType0
        from ..models.build_notification_type_0 import BuildNotificationType0
        from ..models.build_stats_type_0 import BuildStatsType0

        id = self.id

        number = self.number

        head = self.head.to_dict()

        base: dict[str, Any] | None
        if isinstance(self.base, BuildGitReference):
            base = self.base.to_dict()
        else:
            base = self.base

        status: str
        if isinstance(self.status, BuildStatusType0) or isinstance(self.status, BuildStatusType1):
            status = self.status.value
        else:
            status = self.status.value

        conclusion: None | str
        if isinstance(self.conclusion, BuildConclusionType0):
            conclusion = self.conclusion.value
        else:
            conclusion = self.conclusion

        stats: dict[str, Any] | None
        if isinstance(self.stats, BuildStatsType0):
            stats = self.stats.to_dict()
        else:
            stats = self.stats

        metadata: dict[str, Any] | None
        if isinstance(self.metadata, BuildMetadataType0):
            metadata = self.metadata.to_dict()
        else:
            metadata = self.metadata

        url = self.url

        notification: dict[str, Any] | None
        if isinstance(self.notification, BuildNotificationType0):
            notification = self.notification.to_dict()
        else:
            notification = self.notification

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "number": number,
                "head": head,
                "base": base,
                "status": status,
                "conclusion": conclusion,
                "stats": stats,
                "metadata": metadata,
                "url": url,
                "notification": notification,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build_git_reference import BuildGitReference
        from ..models.build_metadata_type_0 import BuildMetadataType0
        from ..models.build_notification_type_0 import BuildNotificationType0
        from ..models.build_stats_type_0 import BuildStatsType0

        d = dict(src_dict)
        id = d.pop("id")

        number = d.pop("number")

        head = BuildGitReference.from_dict(d.pop("head"))

        def _parse_base(data: object) -> BuildGitReference | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                base_type_0 = BuildGitReference.from_dict(data)

                return base_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(BuildGitReference | None, data)

        base = _parse_base(d.pop("base"))

        def _parse_status(data: object) -> BuildStatusType0 | BuildStatusType1 | BuildStatusType2:
            try:
                if not isinstance(data, str):
                    raise TypeError()
                status_type_0 = BuildStatusType0(data)

                return status_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            try:
                if not isinstance(data, str):
                    raise TypeError()
                status_type_1 = BuildStatusType1(data)

                return status_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            if not isinstance(data, str):
                raise TypeError()
            status_type_2 = BuildStatusType2(data)

            return status_type_2

        status = _parse_status(d.pop("status"))

        def _parse_conclusion(data: object) -> BuildConclusionType0 | None:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                conclusion_type_0 = BuildConclusionType0(data)

                return conclusion_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(BuildConclusionType0 | None, data)

        conclusion = _parse_conclusion(d.pop("conclusion"))

        def _parse_stats(data: object) -> BuildStatsType0 | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                stats_type_0 = BuildStatsType0.from_dict(data)

                return stats_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(BuildStatsType0 | None, data)

        stats = _parse_stats(d.pop("stats"))

        def _parse_metadata(data: object) -> BuildMetadataType0 | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                metadata_type_0 = BuildMetadataType0.from_dict(data)

                return metadata_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(BuildMetadataType0 | None, data)

        metadata = _parse_metadata(d.pop("metadata"))

        url = d.pop("url")

        def _parse_notification(data: object) -> BuildNotificationType0 | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                notification_type_0 = BuildNotificationType0.from_dict(data)

                return notification_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(BuildNotificationType0 | None, data)

        notification = _parse_notification(d.pop("notification"))

        build = cls(
            id=id,
            number=number,
            head=head,
            base=base,
            status=status,
            conclusion=conclusion,
            stats=stats,
            metadata=metadata,
            url=url,
            notification=notification,
        )

        return build
