# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

from ..models.build_metadata_type_0_test_report_status import BuildMetadataType0TestReportStatus
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.build_metadata_type_0_test_report_stats import BuildMetadataType0TestReportStats


T = TypeVar("T", bound="BuildMetadataType0TestReport")


@_attrs_define
class BuildMetadataType0TestReport:
    """Test suite report

    Attributes:
        status (BuildMetadataType0TestReportStatus): Status of the test suite
        stats (BuildMetadataType0TestReportStats | Unset):
    """

    status: BuildMetadataType0TestReportStatus
    stats: BuildMetadataType0TestReportStats | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        status = self.status.value

        stats: dict[str, Any] | Unset = UNSET
        if not isinstance(self.stats, Unset):
            stats = self.stats.to_dict()

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "status": status,
            }
        )
        if stats is not UNSET:
            field_dict["stats"] = stats

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build_metadata_type_0_test_report_stats import (
            BuildMetadataType0TestReportStats,
        )

        d = dict(src_dict)
        status = BuildMetadataType0TestReportStatus(d.pop("status"))

        _stats = d.pop("stats", UNSET)
        stats: BuildMetadataType0TestReportStats | Unset
        if isinstance(_stats, Unset):
            stats = UNSET
        else:
            stats = BuildMetadataType0TestReportStats.from_dict(_stats)

        build_metadata_type_0_test_report = cls(
            status=status,
            stats=stats,
        )

        return build_metadata_type_0_test_report
