# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.build_metadata_type_0_test_report import BuildMetadataType0TestReport


T = TypeVar("T", bound="BuildMetadataType0")


@_attrs_define
class BuildMetadataType0:
    """Metadata associated to the build

    Attributes:
        test_report (BuildMetadataType0TestReport | Unset): Test suite report
    """

    test_report: BuildMetadataType0TestReport | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        test_report: dict[str, Any] | Unset = UNSET
        if not isinstance(self.test_report, Unset):
            test_report = self.test_report.to_dict()

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if test_report is not UNSET:
            field_dict["testReport"] = test_report

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build_metadata_type_0_test_report import BuildMetadataType0TestReport

        d = dict(src_dict)
        _test_report = d.pop("testReport", UNSET)
        test_report: BuildMetadataType0TestReport | Unset
        if isinstance(_test_report, Unset):
            test_report = UNSET
        else:
            test_report = BuildMetadataType0TestReport.from_dict(_test_report)

        build_metadata_type_0 = cls(
            test_report=test_report,
        )

        return build_metadata_type_0
