# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

from ..models.build_review_state import BuildReviewState

if TYPE_CHECKING:
    from ..models.build_review_user import BuildReviewUser


T = TypeVar("T", bound="BuildReview")


@_attrs_define
class BuildReview:
    """Build review

    Attributes:
        id (str):
        build_id (str):
        state (BuildReviewState):
        user (BuildReviewUser | None): The user who submitted the review.
        dismissed_at (None | str): Date the review was dismissed, null if not dismissed.
        dismissed_by (BuildReviewUser | None): The user who dismissed the review, if any.
        date (str): Date the review was created.
    """

    id: str
    build_id: str
    state: BuildReviewState
    user: BuildReviewUser | None
    dismissed_at: None | str
    dismissed_by: BuildReviewUser | None
    date: str

    def to_dict(self) -> dict[str, Any]:
        from ..models.build_review_user import BuildReviewUser

        id = self.id

        build_id = self.build_id

        state = self.state.value

        user: dict[str, Any] | None
        if isinstance(self.user, BuildReviewUser):
            user = self.user.to_dict()
        else:
            user = self.user

        dismissed_at: None | str
        dismissed_at = self.dismissed_at

        dismissed_by: dict[str, Any] | None
        if isinstance(self.dismissed_by, BuildReviewUser):
            dismissed_by = self.dismissed_by.to_dict()
        else:
            dismissed_by = self.dismissed_by

        date = self.date

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "buildId": build_id,
                "state": state,
                "user": user,
                "dismissedAt": dismissed_at,
                "dismissedBy": dismissed_by,
                "date": date,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build_review_user import BuildReviewUser

        d = dict(src_dict)
        id = d.pop("id")

        build_id = d.pop("buildId")

        state = BuildReviewState(d.pop("state"))

        def _parse_user(data: object) -> BuildReviewUser | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                user_type_0 = BuildReviewUser.from_dict(data)

                return user_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(BuildReviewUser | None, data)

        user = _parse_user(d.pop("user"))

        def _parse_dismissed_at(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        dismissed_at = _parse_dismissed_at(d.pop("dismissedAt"))

        def _parse_dismissed_by(data: object) -> BuildReviewUser | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                dismissed_by_type_0 = BuildReviewUser.from_dict(data)

                return dismissed_by_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(BuildReviewUser | None, data)

        dismissed_by = _parse_dismissed_by(d.pop("dismissedBy"))

        date = d.pop("date")

        build_review = cls(
            id=id,
            build_id=build_id,
            state=state,
            user=user,
            dismissed_at=dismissed_at,
            dismissed_by=dismissed_by,
            date=date,
        )

        return build_review
