# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="Change")


@_attrs_define
class Change:
    """A test change: a specific visual difference (fingerprint) of a test that can be ignored to silence flaky changes.

    Attributes:
        id (str): Unique identifier of the change (a test + fingerprint pair). Use it with the ignore/unignore
            endpoints.
        ignored (bool): Whether this change is currently ignored. Ignored changes no longer require review and are
            automatically approved.
        occurrences (float): Number of times this change has been seen over the metrics period. A high count for a
            recurring change is a strong flakiness signal.
    """

    id: str
    ignored: bool
    occurrences: float

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        ignored = self.ignored

        occurrences = self.occurrences

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "ignored": ignored,
                "occurrences": occurrences,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        ignored = d.pop("ignored")

        occurrences = d.pop("occurrences")

        change = cls(
            id=id,
            ignored=ignored,
            occurrences=occurrences,
        )

        return change
