# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Literal, TypeVar, cast

from attrs import define as _attrs_define

T = TypeVar("T", bound="CommentAnchorType0Type0")


@_attrs_define
class CommentAnchorType0Type0:
    """
    Attributes:
        type_ (Literal['point']):
        x (float):
        y (float):
    """

    type_: Literal["point"]
    x: float
    y: float

    def to_dict(self) -> dict[str, Any]:
        type_ = self.type_

        x = self.x

        y = self.y

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "type": type_,
                "x": x,
                "y": y,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        type_ = cast(Literal["point"], d.pop("type"))
        if type_ != "point":
            raise ValueError(f"type must match const 'point', got '{type_}'")

        x = d.pop("x")

        y = d.pop("y")

        comment_anchor_type_0_type_0 = cls(
            type_=type_,
            x=x,
            y=y,
        )

        return comment_anchor_type_0_type_0
