# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.user import User


T = TypeVar("T", bound="CommentReactionsItem")


@_attrs_define
class CommentReactionsItem:
    """Reactions of a single emoji on a comment.

    Attributes:
        emoji (str): The emoji used for the reaction.
        count (float): Number of users who reacted with this emoji.
        users (list[User]): The users who reacted with this emoji.
    """

    emoji: str
    count: float
    users: list[User]

    def to_dict(self) -> dict[str, Any]:
        emoji = self.emoji

        count = self.count

        users = []
        for users_item_data in self.users:
            users_item = users_item_data.to_dict()
            users.append(users_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "emoji": emoji,
                "count": count,
                "users": users,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.user import User

        d = dict(src_dict)
        emoji = d.pop("emoji")

        count = d.pop("count")

        users = []
        _users = d.pop("users")
        for users_item_data in _users:
            users_item = User.from_dict(users_item_data)

            users.append(users_item)

        comment_reactions_item = cls(
            emoji=emoji,
            count=count,
            users=users,
        )

        return comment_reactions_item
