# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.comment_anchor_type_0_type_0 import CommentAnchorType0Type0
    from ..models.comment_anchor_type_0_type_1 import CommentAnchorType0Type1
    from ..models.comment_reactions_item import CommentReactionsItem
    from ..models.user import User


T = TypeVar("T", bound="Comment")


@_attrs_define
class Comment:
    """A comment posted on a build.

    Attributes:
        id (str):
        build_id (str):
        thread_id (None | str): Root comment ID when this comment is a reply.
        body (Any): Rich-text JSON content of the comment.
        text (str): Plain-text rendering of the comment content.
        author (None | User):
        screenshot_diff_id (None | str): Screenshot diff this comment is anchored to, if any.
        anchor (CommentAnchorType0Type0 | CommentAnchorType0Type1 | None): Where the comment points on its screenshot
            diff. Null means the whole diff.
        pending (bool): Whether the comment belongs to a pending (unsubmitted) review and is only visible to its author.
        resolved_at (None | str): Date the thread was resolved, null if not resolved. Only set on a root comment.
        edited_at (None | str): Date the comment was last edited, null if never edited.
        created_at (str): Date the comment was posted.
        reactions (list[CommentReactionsItem]):
    """

    id: str
    build_id: str
    thread_id: None | str
    body: Any
    text: str
    author: None | User
    screenshot_diff_id: None | str
    anchor: CommentAnchorType0Type0 | CommentAnchorType0Type1 | None
    pending: bool
    resolved_at: None | str
    edited_at: None | str
    created_at: str
    reactions: list[CommentReactionsItem]

    def to_dict(self) -> dict[str, Any]:
        from ..models.comment_anchor_type_0_type_0 import CommentAnchorType0Type0
        from ..models.comment_anchor_type_0_type_1 import CommentAnchorType0Type1
        from ..models.user import User

        id = self.id

        build_id = self.build_id

        thread_id: None | str
        thread_id = self.thread_id

        body = self.body

        text = self.text

        author: dict[str, Any] | None
        if isinstance(self.author, User):
            author = self.author.to_dict()
        else:
            author = self.author

        screenshot_diff_id: None | str
        screenshot_diff_id = self.screenshot_diff_id

        anchor: dict[str, Any] | None
        if isinstance(self.anchor, CommentAnchorType0Type0) or isinstance(
            self.anchor, CommentAnchorType0Type1
        ):
            anchor = self.anchor.to_dict()
        else:
            anchor = self.anchor

        pending = self.pending

        resolved_at: None | str
        resolved_at = self.resolved_at

        edited_at: None | str
        edited_at = self.edited_at

        created_at = self.created_at

        reactions = []
        for reactions_item_data in self.reactions:
            reactions_item = reactions_item_data.to_dict()
            reactions.append(reactions_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "buildId": build_id,
                "threadId": thread_id,
                "body": body,
                "text": text,
                "author": author,
                "screenshotDiffId": screenshot_diff_id,
                "anchor": anchor,
                "pending": pending,
                "resolvedAt": resolved_at,
                "editedAt": edited_at,
                "createdAt": created_at,
                "reactions": reactions,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.comment_anchor_type_0_type_0 import CommentAnchorType0Type0
        from ..models.comment_anchor_type_0_type_1 import CommentAnchorType0Type1
        from ..models.comment_reactions_item import CommentReactionsItem
        from ..models.user import User

        d = dict(src_dict)
        id = d.pop("id")

        build_id = d.pop("buildId")

        def _parse_thread_id(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        thread_id = _parse_thread_id(d.pop("threadId"))

        body = d.pop("body")

        text = d.pop("text")

        def _parse_author(data: object) -> None | User:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                author_type_0 = User.from_dict(data)

                return author_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | User, data)

        author = _parse_author(d.pop("author"))

        def _parse_screenshot_diff_id(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        screenshot_diff_id = _parse_screenshot_diff_id(d.pop("screenshotDiffId"))

        def _parse_anchor(data: object) -> CommentAnchorType0Type0 | CommentAnchorType0Type1 | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                anchor_type_0_type_0 = CommentAnchorType0Type0.from_dict(data)

                return anchor_type_0_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                anchor_type_0_type_1 = CommentAnchorType0Type1.from_dict(data)

                return anchor_type_0_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(CommentAnchorType0Type0 | CommentAnchorType0Type1 | None, data)

        anchor = _parse_anchor(d.pop("anchor"))

        pending = d.pop("pending")

        def _parse_resolved_at(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        resolved_at = _parse_resolved_at(d.pop("resolvedAt"))

        def _parse_edited_at(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        edited_at = _parse_edited_at(d.pop("editedAt"))

        created_at = d.pop("createdAt")

        reactions = []
        _reactions = d.pop("reactions")
        for reactions_item_data in _reactions:
            reactions_item = CommentReactionsItem.from_dict(reactions_item_data)

            reactions.append(reactions_item)

        comment = cls(
            id=id,
            build_id=build_id,
            thread_id=thread_id,
            body=body,
            text=text,
            author=author,
            screenshot_diff_id=screenshot_diff_id,
            anchor=anchor,
            pending=pending,
            resolved_at=resolved_at,
            edited_at=edited_at,
            created_at=created_at,
            reactions=reactions,
        )

        return comment
