# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Literal, TypeVar, cast

from attrs import define as _attrs_define

T = TypeVar("T", bound="CommentAnchorType0Type1")


@_attrs_define
class CommentAnchorType0Type1:
    """
    Attributes:
        type_ (Literal['lines']):
        from_ (int):
        to (int):
    """

    type_: Literal["lines"]
    from_: int
    to: int

    def to_dict(self) -> dict[str, Any]:
        type_ = self.type_

        from_ = self.from_

        to = self.to

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "type": type_,
                "from": from_,
                "to": to,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        type_ = cast(Literal["lines"], d.pop("type"))
        if type_ != "lines":
            raise ValueError(f"type must match const 'lines', got '{type_}'")

        from_ = d.pop("from")

        to = d.pop("to")

        comment_anchor_type_0_type_1 = cls(
            type_=type_,
            from_=from_,
            to=to,
        )

        return comment_anchor_type_0_type_1
