# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.create_review_body_snapshots_item_conclusion import (
    CreateReviewBodySnapshotsItemConclusion,
)

T = TypeVar("T", bound="CreateReviewBodySnapshotsItem")


@_attrs_define
class CreateReviewBodySnapshotsItem:
    """
    Attributes:
        id (str): The ID of the snapshot to review
        conclusion (CreateReviewBodySnapshotsItemConclusion): Review conclusion for this individual snapshot: "APPROVE"
            or "REQUEST_CHANGES"
    """

    id: str
    conclusion: CreateReviewBodySnapshotsItemConclusion
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        conclusion = self.conclusion.value

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "conclusion": conclusion,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        conclusion = CreateReviewBodySnapshotsItemConclusion(d.pop("conclusion"))

        create_review_body_snapshots_item = cls(
            id=id,
            conclusion=conclusion,
        )

        create_review_body_snapshots_item.additional_properties = d
        return create_review_body_snapshots_item

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
