# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.create_build_response_201_screenshots_item_type_1_fields import (
        CreateBuildResponse201ScreenshotsItemType1Fields,
    )


T = TypeVar("T", bound="CreateBuildResponse201ScreenshotsItemType1")


@_attrs_define
class CreateBuildResponse201ScreenshotsItemType1:
    """
    Attributes:
        key (str):
        post_url (str):
        fields (CreateBuildResponse201ScreenshotsItemType1Fields):
    """

    key: str
    post_url: str
    fields: CreateBuildResponse201ScreenshotsItemType1Fields

    def to_dict(self) -> dict[str, Any]:
        key = self.key

        post_url = self.post_url

        fields = self.fields.to_dict()

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "key": key,
                "postUrl": post_url,
                "fields": fields,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.create_build_response_201_screenshots_item_type_1_fields import (
            CreateBuildResponse201ScreenshotsItemType1Fields,
        )

        d = dict(src_dict)
        key = d.pop("key")

        post_url = d.pop("postUrl")

        fields = CreateBuildResponse201ScreenshotsItemType1Fields.from_dict(d.pop("fields"))

        create_build_response_201_screenshots_item_type_1 = cls(
            key=key,
            post_url=post_url,
            fields=fields,
        )

        return create_build_response_201_screenshots_item_type_1
