# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.build import Build
    from ..models.create_build_response_201_pw_traces_item_type_0 import (
        CreateBuildResponse201PwTracesItemType0,
    )
    from ..models.create_build_response_201_pw_traces_item_type_1 import (
        CreateBuildResponse201PwTracesItemType1,
    )
    from ..models.create_build_response_201_screenshots_item_type_0 import (
        CreateBuildResponse201ScreenshotsItemType0,
    )
    from ..models.create_build_response_201_screenshots_item_type_1 import (
        CreateBuildResponse201ScreenshotsItemType1,
    )


T = TypeVar("T", bound="CreateBuildResponse201")


@_attrs_define
class CreateBuildResponse201:
    """
    Attributes:
        build (Build): Build
        screenshots (list[CreateBuildResponse201ScreenshotsItemType0 | CreateBuildResponse201ScreenshotsItemType1]):
        pw_traces (list[CreateBuildResponse201PwTracesItemType0 | CreateBuildResponse201PwTracesItemType1]):
    """

    build: Build
    screenshots: list[
        CreateBuildResponse201ScreenshotsItemType0 | CreateBuildResponse201ScreenshotsItemType1
    ]
    pw_traces: list[
        CreateBuildResponse201PwTracesItemType0 | CreateBuildResponse201PwTracesItemType1
    ]

    def to_dict(self) -> dict[str, Any]:
        from ..models.create_build_response_201_pw_traces_item_type_0 import (
            CreateBuildResponse201PwTracesItemType0,
        )
        from ..models.create_build_response_201_screenshots_item_type_0 import (
            CreateBuildResponse201ScreenshotsItemType0,
        )

        build = self.build.to_dict()

        screenshots = []
        for screenshots_item_data in self.screenshots:
            screenshots_item: dict[str, Any]
            if isinstance(screenshots_item_data, CreateBuildResponse201ScreenshotsItemType0):
                screenshots_item = screenshots_item_data.to_dict()
            else:
                screenshots_item = screenshots_item_data.to_dict()

            screenshots.append(screenshots_item)

        pw_traces = []
        for pw_traces_item_data in self.pw_traces:
            pw_traces_item: dict[str, Any]
            if isinstance(pw_traces_item_data, CreateBuildResponse201PwTracesItemType0):
                pw_traces_item = pw_traces_item_data.to_dict()
            else:
                pw_traces_item = pw_traces_item_data.to_dict()

            pw_traces.append(pw_traces_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "build": build,
                "screenshots": screenshots,
                "pwTraces": pw_traces,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build import Build
        from ..models.create_build_response_201_pw_traces_item_type_0 import (
            CreateBuildResponse201PwTracesItemType0,
        )
        from ..models.create_build_response_201_pw_traces_item_type_1 import (
            CreateBuildResponse201PwTracesItemType1,
        )
        from ..models.create_build_response_201_screenshots_item_type_0 import (
            CreateBuildResponse201ScreenshotsItemType0,
        )
        from ..models.create_build_response_201_screenshots_item_type_1 import (
            CreateBuildResponse201ScreenshotsItemType1,
        )

        d = dict(src_dict)
        build = Build.from_dict(d.pop("build"))

        screenshots = []
        _screenshots = d.pop("screenshots")
        for screenshots_item_data in _screenshots:

            def _parse_screenshots_item(
                data: object,
            ) -> (
                CreateBuildResponse201ScreenshotsItemType0
                | CreateBuildResponse201ScreenshotsItemType1
            ):
                try:
                    if not isinstance(data, dict):
                        raise TypeError()
                    screenshots_item_type_0 = CreateBuildResponse201ScreenshotsItemType0.from_dict(
                        data
                    )

                    return screenshots_item_type_0
                except (TypeError, ValueError, AttributeError, KeyError):
                    pass
                if not isinstance(data, dict):
                    raise TypeError()
                screenshots_item_type_1 = CreateBuildResponse201ScreenshotsItemType1.from_dict(data)

                return screenshots_item_type_1

            screenshots_item = _parse_screenshots_item(screenshots_item_data)

            screenshots.append(screenshots_item)

        pw_traces = []
        _pw_traces = d.pop("pwTraces")
        for pw_traces_item_data in _pw_traces:

            def _parse_pw_traces_item(
                data: object,
            ) -> CreateBuildResponse201PwTracesItemType0 | CreateBuildResponse201PwTracesItemType1:
                try:
                    if not isinstance(data, dict):
                        raise TypeError()
                    pw_traces_item_type_0 = CreateBuildResponse201PwTracesItemType0.from_dict(data)

                    return pw_traces_item_type_0
                except (TypeError, ValueError, AttributeError, KeyError):
                    pass
                if not isinstance(data, dict):
                    raise TypeError()
                pw_traces_item_type_1 = CreateBuildResponse201PwTracesItemType1.from_dict(data)

                return pw_traces_item_type_1

            pw_traces_item = _parse_pw_traces_item(pw_traces_item_data)

            pw_traces.append(pw_traces_item)

        create_build_response_201 = cls(
            build=build,
            screenshots=screenshots,
            pw_traces=pw_traces,
        )

        return create_build_response_201
