# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.create_build_body_mode_type_0 import CreateBuildBodyModeType0
from ..types import UNSET, Unset

T = TypeVar("T", bound="CreateBuildBody")


@_attrs_define
class CreateBuildBody:
    """
    Attributes:
        commit (str): SHA1 hash
        branch (str):
        pw_trace_keys (list[str] | Unset): Keys of Playwright trace files
        name (None | str | Unset): The name of the build (for multi-build setups)
        parallel (bool | None | Unset): Whether to run the build in parallel
        parallel_nonce (None | str | Unset): A unique nonce for the parallel build
        pr_number (int | None | Unset): The pull request number
        pr_head_commit (None | str | Unset): The head commit of the pull request
        reference_commit (None | str | Unset): The commit to use as a reference for the build
        reference_branch (None | str | Unset): The branch to use as a reference for the build
        parent_commits (list[str] | None | Unset): The parent commits of the build
        mode (CreateBuildBodyModeType0 | None | Unset): The mode in which the build is running
        ci_provider (None | str | Unset): The CI provider being used
        argos_sdk (None | str | Unset): The version of the Snapvisor SDK being used
        run_id (None | str | Unset): The ID of the current run
        run_attempt (int | None | Unset): The attempt number of the current run
        skipped (bool | None | Unset): Whether the build was skipped, not comparing anything and always succeeding
        merge_queue (bool | None | Unset): Whether the build has been created in a merge queue
        merge_queue_pr_numbers (list[int] | None | Unset): Pull request numbers aggregated by the merge queue build.
            Requires `mergeQueue` to be `true`.
        subset (bool | None | Unset): Indicates whether this build contains only a subset of screenshots.
            This is useful when a build is created from an incomplete test suite where some tests are skipped.
    """

    commit: str
    branch: str
    pw_trace_keys: list[str] | Unset = UNSET
    name: None | str | Unset = UNSET
    parallel: bool | None | Unset = UNSET
    parallel_nonce: None | str | Unset = UNSET
    pr_number: int | None | Unset = UNSET
    pr_head_commit: None | str | Unset = UNSET
    reference_commit: None | str | Unset = UNSET
    reference_branch: None | str | Unset = UNSET
    parent_commits: list[str] | None | Unset = UNSET
    mode: CreateBuildBodyModeType0 | None | Unset = UNSET
    ci_provider: None | str | Unset = UNSET
    argos_sdk: None | str | Unset = UNSET
    run_id: None | str | Unset = UNSET
    run_attempt: int | None | Unset = UNSET
    skipped: bool | None | Unset = UNSET
    merge_queue: bool | None | Unset = UNSET
    merge_queue_pr_numbers: list[int] | None | Unset = UNSET
    subset: bool | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        commit = self.commit

        branch = self.branch

        pw_trace_keys: list[str] | Unset = UNSET
        if not isinstance(self.pw_trace_keys, Unset):
            pw_trace_keys = self.pw_trace_keys

        name: None | str | Unset
        if isinstance(self.name, Unset):
            name = UNSET
        else:
            name = self.name

        parallel: bool | None | Unset
        if isinstance(self.parallel, Unset):
            parallel = UNSET
        else:
            parallel = self.parallel

        parallel_nonce: None | str | Unset
        if isinstance(self.parallel_nonce, Unset):
            parallel_nonce = UNSET
        else:
            parallel_nonce = self.parallel_nonce

        pr_number: int | None | Unset
        if isinstance(self.pr_number, Unset):
            pr_number = UNSET
        else:
            pr_number = self.pr_number

        pr_head_commit: None | str | Unset
        if isinstance(self.pr_head_commit, Unset):
            pr_head_commit = UNSET
        else:
            pr_head_commit = self.pr_head_commit

        reference_commit: None | str | Unset
        if isinstance(self.reference_commit, Unset):
            reference_commit = UNSET
        else:
            reference_commit = self.reference_commit

        reference_branch: None | str | Unset
        if isinstance(self.reference_branch, Unset):
            reference_branch = UNSET
        else:
            reference_branch = self.reference_branch

        parent_commits: list[str] | None | Unset
        if isinstance(self.parent_commits, Unset):
            parent_commits = UNSET
        elif isinstance(self.parent_commits, list):
            parent_commits = self.parent_commits

        else:
            parent_commits = self.parent_commits

        mode: None | str | Unset
        if isinstance(self.mode, Unset):
            mode = UNSET
        elif isinstance(self.mode, CreateBuildBodyModeType0):
            mode = self.mode.value
        else:
            mode = self.mode

        ci_provider: None | str | Unset
        if isinstance(self.ci_provider, Unset):
            ci_provider = UNSET
        else:
            ci_provider = self.ci_provider

        argos_sdk: None | str | Unset
        if isinstance(self.argos_sdk, Unset):
            argos_sdk = UNSET
        else:
            argos_sdk = self.argos_sdk

        run_id: None | str | Unset
        if isinstance(self.run_id, Unset):
            run_id = UNSET
        else:
            run_id = self.run_id

        run_attempt: int | None | Unset
        if isinstance(self.run_attempt, Unset):
            run_attempt = UNSET
        else:
            run_attempt = self.run_attempt

        skipped: bool | None | Unset
        if isinstance(self.skipped, Unset):
            skipped = UNSET
        else:
            skipped = self.skipped

        merge_queue: bool | None | Unset
        if isinstance(self.merge_queue, Unset):
            merge_queue = UNSET
        else:
            merge_queue = self.merge_queue

        merge_queue_pr_numbers: list[int] | None | Unset
        if isinstance(self.merge_queue_pr_numbers, Unset):
            merge_queue_pr_numbers = UNSET
        elif isinstance(self.merge_queue_pr_numbers, list):
            merge_queue_pr_numbers = self.merge_queue_pr_numbers

        else:
            merge_queue_pr_numbers = self.merge_queue_pr_numbers

        subset: bool | None | Unset
        if isinstance(self.subset, Unset):
            subset = UNSET
        else:
            subset = self.subset

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "commit": commit,
                "branch": branch,
            }
        )
        if pw_trace_keys is not UNSET:
            field_dict["pwTraceKeys"] = pw_trace_keys
        if name is not UNSET:
            field_dict["name"] = name
        if parallel is not UNSET:
            field_dict["parallel"] = parallel
        if parallel_nonce is not UNSET:
            field_dict["parallelNonce"] = parallel_nonce
        if pr_number is not UNSET:
            field_dict["prNumber"] = pr_number
        if pr_head_commit is not UNSET:
            field_dict["prHeadCommit"] = pr_head_commit
        if reference_commit is not UNSET:
            field_dict["referenceCommit"] = reference_commit
        if reference_branch is not UNSET:
            field_dict["referenceBranch"] = reference_branch
        if parent_commits is not UNSET:
            field_dict["parentCommits"] = parent_commits
        if mode is not UNSET:
            field_dict["mode"] = mode
        if ci_provider is not UNSET:
            field_dict["ciProvider"] = ci_provider
        if argos_sdk is not UNSET:
            field_dict["argosSdk"] = argos_sdk
        if run_id is not UNSET:
            field_dict["runId"] = run_id
        if run_attempt is not UNSET:
            field_dict["runAttempt"] = run_attempt
        if skipped is not UNSET:
            field_dict["skipped"] = skipped
        if merge_queue is not UNSET:
            field_dict["mergeQueue"] = merge_queue
        if merge_queue_pr_numbers is not UNSET:
            field_dict["mergeQueuePrNumbers"] = merge_queue_pr_numbers
        if subset is not UNSET:
            field_dict["subset"] = subset

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        commit = d.pop("commit")

        branch = d.pop("branch")

        pw_trace_keys = cast(list[str], d.pop("pwTraceKeys", UNSET))

        def _parse_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        name = _parse_name(d.pop("name", UNSET))

        def _parse_parallel(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        parallel = _parse_parallel(d.pop("parallel", UNSET))

        def _parse_parallel_nonce(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        parallel_nonce = _parse_parallel_nonce(d.pop("parallelNonce", UNSET))

        def _parse_pr_number(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        pr_number = _parse_pr_number(d.pop("prNumber", UNSET))

        def _parse_pr_head_commit(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        pr_head_commit = _parse_pr_head_commit(d.pop("prHeadCommit", UNSET))

        def _parse_reference_commit(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        reference_commit = _parse_reference_commit(d.pop("referenceCommit", UNSET))

        def _parse_reference_branch(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        reference_branch = _parse_reference_branch(d.pop("referenceBranch", UNSET))

        def _parse_parent_commits(data: object) -> list[str] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                parent_commits_type_0 = cast(list[str], data)

                return parent_commits_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[str] | None | Unset, data)

        parent_commits = _parse_parent_commits(d.pop("parentCommits", UNSET))

        def _parse_mode(data: object) -> CreateBuildBodyModeType0 | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                mode_type_0 = CreateBuildBodyModeType0(data)

                return mode_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(CreateBuildBodyModeType0 | None | Unset, data)

        mode = _parse_mode(d.pop("mode", UNSET))

        def _parse_ci_provider(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        ci_provider = _parse_ci_provider(d.pop("ciProvider", UNSET))

        def _parse_argos_sdk(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        argos_sdk = _parse_argos_sdk(d.pop("argosSdk", UNSET))

        def _parse_run_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        run_id = _parse_run_id(d.pop("runId", UNSET))

        def _parse_run_attempt(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        run_attempt = _parse_run_attempt(d.pop("runAttempt", UNSET))

        def _parse_skipped(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        skipped = _parse_skipped(d.pop("skipped", UNSET))

        def _parse_merge_queue(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        merge_queue = _parse_merge_queue(d.pop("mergeQueue", UNSET))

        def _parse_merge_queue_pr_numbers(data: object) -> list[int] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                merge_queue_pr_numbers_type_0 = cast(list[int], data)

                return merge_queue_pr_numbers_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[int] | None | Unset, data)

        merge_queue_pr_numbers = _parse_merge_queue_pr_numbers(d.pop("mergeQueuePrNumbers", UNSET))

        def _parse_subset(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        subset = _parse_subset(d.pop("subset", UNSET))

        create_build_body = cls(
            commit=commit,
            branch=branch,
            pw_trace_keys=pw_trace_keys,
            name=name,
            parallel=parallel,
            parallel_nonce=parallel_nonce,
            pr_number=pr_number,
            pr_head_commit=pr_head_commit,
            reference_commit=reference_commit,
            reference_branch=reference_branch,
            parent_commits=parent_commits,
            mode=mode,
            ci_provider=ci_provider,
            argos_sdk=argos_sdk,
            run_id=run_id,
            run_attempt=run_attempt,
            skipped=skipped,
            merge_queue=merge_queue,
            merge_queue_pr_numbers=merge_queue_pr_numbers,
            subset=subset,
        )

        create_build_body.additional_properties = d
        return create_build_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
