# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.create_deployment_body_environment import CreateDeploymentBodyEnvironment
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.create_deployment_body_files_item import CreateDeploymentBodyFilesItem


T = TypeVar("T", bound="CreateDeploymentBody")


@_attrs_define
class CreateDeploymentBody:
    """
    Attributes:
        commit (str): SHA1 hash
        branch (str):
        files (list[CreateDeploymentBodyFilesItem]): List of files to deploy
        pr_number (int | None | Unset): The pull request number
        environment (CreateDeploymentBodyEnvironment | Unset): The deployment environment. When omitted, it is inferred
            from `branch`: branches matching the configured production-branch glob are treated as `production`; all others
            default to `preview`.
    """

    commit: str
    branch: str
    files: list[CreateDeploymentBodyFilesItem]
    pr_number: int | None | Unset = UNSET
    environment: CreateDeploymentBodyEnvironment | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        commit = self.commit

        branch = self.branch

        files = []
        for files_item_data in self.files:
            files_item = files_item_data.to_dict()
            files.append(files_item)

        pr_number: int | None | Unset
        if isinstance(self.pr_number, Unset):
            pr_number = UNSET
        else:
            pr_number = self.pr_number

        environment: str | Unset = UNSET
        if not isinstance(self.environment, Unset):
            environment = self.environment.value

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "commit": commit,
                "branch": branch,
                "files": files,
            }
        )
        if pr_number is not UNSET:
            field_dict["prNumber"] = pr_number
        if environment is not UNSET:
            field_dict["environment"] = environment

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.create_deployment_body_files_item import CreateDeploymentBodyFilesItem

        d = dict(src_dict)
        commit = d.pop("commit")

        branch = d.pop("branch")

        files = []
        _files = d.pop("files")
        for files_item_data in _files:
            files_item = CreateDeploymentBodyFilesItem.from_dict(files_item_data)

            files.append(files_item)

        def _parse_pr_number(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        pr_number = _parse_pr_number(d.pop("prNumber", UNSET))

        _environment = d.pop("environment", UNSET)
        environment: CreateDeploymentBodyEnvironment | Unset
        if isinstance(_environment, Unset):
            environment = UNSET
        else:
            environment = CreateDeploymentBodyEnvironment(_environment)

        create_deployment_body = cls(
            commit=commit,
            branch=branch,
            files=files,
            pr_number=pr_number,
            environment=environment,
        )

        create_deployment_body.additional_properties = d
        return create_deployment_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
