# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.create_deployment_response_201_upload_files_item import (
        CreateDeploymentResponse201UploadFilesItem,
    )


T = TypeVar("T", bound="CreateDeploymentResponse201")


@_attrs_define
class CreateDeploymentResponse201:
    """
    Attributes:
        deployment_id (str):
        upload_files (list[CreateDeploymentResponse201UploadFilesItem]):
    """

    deployment_id: str
    upload_files: list[CreateDeploymentResponse201UploadFilesItem]

    def to_dict(self) -> dict[str, Any]:

        deployment_id = self.deployment_id

        upload_files = []
        for upload_files_item_data in self.upload_files:
            upload_files_item = upload_files_item_data.to_dict()
            upload_files.append(upload_files_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "deploymentId": deployment_id,
                "uploadFiles": upload_files,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.create_deployment_response_201_upload_files_item import (
            CreateDeploymentResponse201UploadFilesItem,
        )

        d = dict(src_dict)
        deployment_id = d.pop("deploymentId")

        upload_files = []
        _upload_files = d.pop("uploadFiles")
        for upload_files_item_data in _upload_files:
            upload_files_item = CreateDeploymentResponse201UploadFilesItem.from_dict(
                upload_files_item_data
            )

            upload_files.append(upload_files_item)

        create_deployment_response_201 = cls(
            deployment_id=deployment_id,
            upload_files=upload_files,
        )

        return create_deployment_response_201
