# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="CreateDeploymentResponse201UploadFilesItem")


@_attrs_define
class CreateDeploymentResponse201UploadFilesItem:
    """
    Attributes:
        path (str):
        hash_ (str):
        upload_url (str):
    """

    path: str
    hash_: str
    upload_url: str

    def to_dict(self) -> dict[str, Any]:
        path = self.path

        hash_ = self.hash_

        upload_url = self.upload_url

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "path": path,
                "hash": hash_,
                "uploadUrl": upload_url,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        path = d.pop("path")

        hash_ = d.pop("hash")

        upload_url = d.pop("uploadUrl")

        create_deployment_response_201_upload_files_item = cls(
            path=path,
            hash_=hash_,
            upload_url=upload_url,
        )

        return create_deployment_response_201_upload_files_item
