# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.create_review_body_conclusion import CreateReviewBodyConclusion
from ..models.create_review_body_event import CreateReviewBodyEvent
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.create_review_body_snapshots_item import CreateReviewBodySnapshotsItem


T = TypeVar("T", bound="CreateReviewBody")


@_attrs_define
class CreateReviewBody:
    """
    Attributes:
        event (CreateReviewBodyEvent | Unset): Review event to apply to the build: "APPROVE", "REJECT" or "COMMENT".
            Required when `conclusion` is not provided.
        conclusion (CreateReviewBodyConclusion | Unset): Deprecated: use `event` instead. Overall review conclusion for
            the build: "APPROVE" or "REQUEST_CHANGES".
        body (Any | Unset): Optional comment to attach to the review. Either Markdown text or the JSON representation of
            a rich-text document.
        snapshots (list[CreateReviewBodySnapshotsItem] | Unset): Optional per-snapshot review decisions. When omitted,
            only the build-level review is recorded.
    """

    event: CreateReviewBodyEvent | Unset = UNSET
    conclusion: CreateReviewBodyConclusion | Unset = UNSET
    body: Any | Unset = UNSET
    snapshots: list[CreateReviewBodySnapshotsItem] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:

        event: str | Unset = UNSET
        if not isinstance(self.event, Unset):
            event = self.event.value

        conclusion: str | Unset = UNSET
        if not isinstance(self.conclusion, Unset):
            conclusion = self.conclusion.value

        body = self.body

        snapshots: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.snapshots, Unset):
            snapshots = []
            for snapshots_item_data in self.snapshots:
                snapshots_item = snapshots_item_data.to_dict()
                snapshots.append(snapshots_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if event is not UNSET:
            field_dict["event"] = event
        if conclusion is not UNSET:
            field_dict["conclusion"] = conclusion
        if body is not UNSET:
            field_dict["body"] = body
        if snapshots is not UNSET:
            field_dict["snapshots"] = snapshots

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.create_review_body_snapshots_item import CreateReviewBodySnapshotsItem

        d = dict(src_dict)
        _event = d.pop("event", UNSET)
        event: CreateReviewBodyEvent | Unset
        if isinstance(_event, Unset):
            event = UNSET
        else:
            event = CreateReviewBodyEvent(_event)

        _conclusion = d.pop("conclusion", UNSET)
        conclusion: CreateReviewBodyConclusion | Unset
        if isinstance(_conclusion, Unset):
            conclusion = UNSET
        else:
            conclusion = CreateReviewBodyConclusion(_conclusion)

        body = d.pop("body", UNSET)

        _snapshots = d.pop("snapshots", UNSET)
        snapshots: list[CreateReviewBodySnapshotsItem] | Unset = UNSET
        if _snapshots is not UNSET:
            snapshots = []
            for snapshots_item_data in _snapshots:
                snapshots_item = CreateReviewBodySnapshotsItem.from_dict(snapshots_item_data)

                snapshots.append(snapshots_item)

        create_review_body = cls(
            event=event,
            conclusion=conclusion,
            body=body,
            snapshots=snapshots,
        )

        create_review_body.additional_properties = d
        return create_review_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
