# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="CreateBuildResponse201PwTracesItemType0")


@_attrs_define
class CreateBuildResponse201PwTracesItemType0:
    """
    Attributes:
        key (str):
        put_url (str): Deprecated. Use postUrl and fields instead.
    """

    key: str
    put_url: str

    def to_dict(self) -> dict[str, Any]:
        key = self.key

        put_url = self.put_url

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "key": key,
                "putUrl": put_url,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        key = d.pop("key")

        put_url = d.pop("putUrl")

        create_build_response_201_pw_traces_item_type_0 = cls(
            key=key,
            put_url=put_url,
        )

        return create_build_response_201_pw_traces_item_type_0
