# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.create_comment_body_anchor_type_0 import CreateCommentBodyAnchorType0
    from ..models.create_comment_body_anchor_type_1 import CreateCommentBodyAnchorType1
    from ..models.create_comment_body_body_type_1 import CreateCommentBodyBodyType1


T = TypeVar("T", bound="CreateCommentBody")


@_attrs_define
class CreateCommentBody:
    """
    Attributes:
        body (CreateCommentBodyBodyType1 | str): Comment content. Either Markdown text or the JSON representation of a
            rich-text document.
        thread_id (str | Unset): Root comment ID to reply to.
        screenshot_diff_id (str | Unset): Screenshot diff to anchor the comment to. Required when anchor is set.
        anchor (CreateCommentBodyAnchorType0 | CreateCommentBodyAnchorType1 | Unset): Where on the referenced screenshot
            diff the comment points. A point uses normalized (0–1) coordinates; lines is a 1-based inclusive range.
        add_to_review (bool | Unset): Attach the comment to your pending review (created if needed) instead of posting
            it immediately. Ignored for replies, which inherit their thread's review.
    """

    body: CreateCommentBodyBodyType1 | str
    thread_id: str | Unset = UNSET
    screenshot_diff_id: str | Unset = UNSET
    anchor: CreateCommentBodyAnchorType0 | CreateCommentBodyAnchorType1 | Unset = UNSET
    add_to_review: bool | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.create_comment_body_anchor_type_0 import CreateCommentBodyAnchorType0
        from ..models.create_comment_body_body_type_1 import CreateCommentBodyBodyType1

        body: dict[str, Any] | str
        if isinstance(self.body, CreateCommentBodyBodyType1):
            body = self.body.to_dict()
        else:
            body = self.body

        thread_id = self.thread_id

        screenshot_diff_id = self.screenshot_diff_id

        anchor: dict[str, Any] | Unset
        if isinstance(self.anchor, Unset):
            anchor = UNSET
        elif isinstance(self.anchor, CreateCommentBodyAnchorType0):
            anchor = self.anchor.to_dict()
        else:
            anchor = self.anchor.to_dict()

        add_to_review = self.add_to_review

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "body": body,
            }
        )
        if thread_id is not UNSET:
            field_dict["threadId"] = thread_id
        if screenshot_diff_id is not UNSET:
            field_dict["screenshotDiffId"] = screenshot_diff_id
        if anchor is not UNSET:
            field_dict["anchor"] = anchor
        if add_to_review is not UNSET:
            field_dict["addToReview"] = add_to_review

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.create_comment_body_anchor_type_0 import CreateCommentBodyAnchorType0
        from ..models.create_comment_body_anchor_type_1 import CreateCommentBodyAnchorType1
        from ..models.create_comment_body_body_type_1 import CreateCommentBodyBodyType1

        d = dict(src_dict)

        def _parse_body(data: object) -> CreateCommentBodyBodyType1 | str:
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                body_type_1 = CreateCommentBodyBodyType1.from_dict(data)

                return body_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(CreateCommentBodyBodyType1 | str, data)

        body = _parse_body(d.pop("body"))

        thread_id = d.pop("threadId", UNSET)

        screenshot_diff_id = d.pop("screenshotDiffId", UNSET)

        def _parse_anchor(
            data: object,
        ) -> CreateCommentBodyAnchorType0 | CreateCommentBodyAnchorType1 | Unset:
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                anchor_type_0 = CreateCommentBodyAnchorType0.from_dict(data)

                return anchor_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            if not isinstance(data, dict):
                raise TypeError()
            anchor_type_1 = CreateCommentBodyAnchorType1.from_dict(data)

            return anchor_type_1

        anchor = _parse_anchor(d.pop("anchor", UNSET))

        add_to_review = d.pop("addToReview", UNSET)

        create_comment_body = cls(
            body=body,
            thread_id=thread_id,
            screenshot_diff_id=screenshot_diff_id,
            anchor=anchor,
            add_to_review=add_to_review,
        )

        create_comment_body.additional_properties = d
        return create_comment_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
