# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.error_details_item import ErrorDetailsItem


T = TypeVar("T", bound="Error")


@_attrs_define
class Error:
    """Error response

    Attributes:
        error (str):
        details (list[ErrorDetailsItem] | Unset):
    """

    error: str
    details: list[ErrorDetailsItem] | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        error = self.error

        details: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.details, Unset):
            details = []
            for details_item_data in self.details:
                details_item = details_item_data.to_dict()
                details.append(details_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "error": error,
            }
        )
        if details is not UNSET:
            field_dict["details"] = details

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.error_details_item import ErrorDetailsItem

        d = dict(src_dict)
        error = d.pop("error")

        _details = d.pop("details", UNSET)
        details: list[ErrorDetailsItem] | Unset = UNSET
        if _details is not UNSET:
            details = []
            for details_item_data in _details:
                details_item = ErrorDetailsItem.from_dict(details_item_data)

                details.append(details_item)

        error = cls(
            error=error,
            details=details,
        )

        return error
