# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="ExchangeGitHubActionsTokenlessTokenBody")


@_attrs_define
class ExchangeGitHubActionsTokenlessTokenBody:
    """
    Attributes:
        tokenless_token (str): Argos tokenless GitHub Actions bearer token
        commit (str): SHA1 hash
        branch (str): Expected branch name
    """

    tokenless_token: str
    commit: str
    branch: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        tokenless_token = self.tokenless_token

        commit = self.commit

        branch = self.branch

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "tokenlessToken": tokenless_token,
                "commit": commit,
                "branch": branch,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        tokenless_token = d.pop("tokenlessToken")

        commit = d.pop("commit")

        branch = d.pop("branch")

        exchange_git_hub_actions_tokenless_token_body = cls(
            tokenless_token=tokenless_token,
            commit=commit,
            branch=branch,
        )

        exchange_git_hub_actions_tokenless_token_body.additional_properties = d
        return exchange_git_hub_actions_tokenless_token_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
