# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="ExchangeGitHubActionsTokenlessTokenResponse200")


@_attrs_define
class ExchangeGitHubActionsTokenlessTokenResponse200:
    """
    Attributes:
        token (str): Short-lived Argos project token
        expires_at (str): Token expiration date as an ISO string
    """

    token: str
    expires_at: str

    def to_dict(self) -> dict[str, Any]:
        token = self.token

        expires_at = self.expires_at

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "token": token,
                "expiresAt": expires_at,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        token = d.pop("token")

        expires_at = d.pop("expiresAt")

        exchange_git_hub_actions_tokenless_token_response_200 = cls(
            token=token,
            expires_at=expires_at,
        )

        return exchange_git_hub_actions_tokenless_token_response_200
