# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="ExchangeCliTokenResponse200")


@_attrs_define
class ExchangeCliTokenResponse200:
    """
    Attributes:
        token (str): Argos API token for CLI use
    """

    token: str

    def to_dict(self) -> dict[str, Any]:
        token = self.token

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "token": token,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        token = d.pop("token")

        exchange_cli_token_response_200 = cls(
            token=token,
        )

        return exchange_cli_token_response_200
