# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="ExchangeGitHubActionsOidcTokenBody")


@_attrs_define
class ExchangeGitHubActionsOidcTokenBody:
    """
    Attributes:
        oidc_token (str): GitHub Actions OIDC token
        repository (str | Unset): GitHub repository in owner/name format
        commit (str | Unset): SHA1 hash
    """

    oidc_token: str
    repository: str | Unset = UNSET
    commit: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        oidc_token = self.oidc_token

        repository = self.repository

        commit = self.commit

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "oidcToken": oidc_token,
            }
        )
        if repository is not UNSET:
            field_dict["repository"] = repository
        if commit is not UNSET:
            field_dict["commit"] = commit

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        oidc_token = d.pop("oidcToken")

        repository = d.pop("repository", UNSET)

        commit = d.pop("commit", UNSET)

        exchange_git_hub_actions_oidc_token_body = cls(
            oidc_token=oidc_token,
            repository=repository,
            commit=commit,
        )

        exchange_git_hub_actions_oidc_token_body.additional_properties = d
        return exchange_git_hub_actions_oidc_token_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
