# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.build import Build


T = TypeVar("T", bound="FinalizeBuildsResponse200")


@_attrs_define
class FinalizeBuildsResponse200:
    """
    Attributes:
        builds (list[Build]):
    """

    builds: list[Build]

    def to_dict(self) -> dict[str, Any]:

        builds = []
        for builds_item_data in self.builds:
            builds_item = builds_item_data.to_dict()
            builds.append(builds_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "builds": builds,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build import Build

        d = dict(src_dict)
        builds = []
        _builds = d.pop("builds")
        for builds_item_data in _builds:
            builds_item = Build.from_dict(builds_item_data)

            builds.append(builds_item)

        finalize_builds_response_200 = cls(
            builds=builds,
        )

        return finalize_builds_response_200
