# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

from ..models.finalize_deployment_response_200_environment import (
    FinalizeDeploymentResponse200Environment,
)
from ..models.finalize_deployment_response_200_status import FinalizeDeploymentResponse200Status

T = TypeVar("T", bound="FinalizeDeploymentResponse200")


@_attrs_define
class FinalizeDeploymentResponse200:
    """
    Attributes:
        id (str):
        status (FinalizeDeploymentResponse200Status):
        environment (FinalizeDeploymentResponse200Environment):
        branch (str):
        commit_sha (str): SHA256 hash
        url (str):
        created_at (str):
    """

    id: str
    status: FinalizeDeploymentResponse200Status
    environment: FinalizeDeploymentResponse200Environment
    branch: str
    commit_sha: str
    url: str
    created_at: str

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        status = self.status.value

        environment = self.environment.value

        branch = self.branch

        commit_sha = self.commit_sha

        url = self.url

        created_at = self.created_at

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "status": status,
                "environment": environment,
                "branch": branch,
                "commitSha": commit_sha,
                "url": url,
                "createdAt": created_at,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        status = FinalizeDeploymentResponse200Status(d.pop("status"))

        environment = FinalizeDeploymentResponse200Environment(d.pop("environment"))

        branch = d.pop("branch")

        commit_sha = d.pop("commitSha")

        url = d.pop("url")

        created_at = d.pop("createdAt")

        finalize_deployment_response_200 = cls(
            id=id,
            status=status,
            environment=environment,
            branch=branch,
            commit_sha=commit_sha,
            url=url,
            created_at=created_at,
        )

        return finalize_deployment_response_200
