# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.build import Build


T = TypeVar("T", bound="FindBaselineResponse200")


@_attrs_define
class FindBaselineResponse200:
    """
    Attributes:
        baseline (Build | None): The eligible baseline build found among the commits, or null when none is found.
    """

    baseline: Build | None

    def to_dict(self) -> dict[str, Any]:
        from ..models.build import Build

        baseline: dict[str, Any] | None
        if isinstance(self.baseline, Build):
            baseline = self.baseline.to_dict()
        else:
            baseline = self.baseline

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "baseline": baseline,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build import Build

        d = dict(src_dict)

        def _parse_baseline(data: object) -> Build | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                baseline_type_0 = Build.from_dict(data)

                return baseline_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(Build | None, data)

        baseline = _parse_baseline(d.pop("baseline"))

        find_baseline_response_200 = cls(
            baseline=baseline,
        )

        return find_baseline_response_200
