# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.find_baseline_body_mode import FindBaselineBodyMode
from ..types import UNSET, Unset

T = TypeVar("T", bound="FindBaselineBody")


@_attrs_define
class FindBaselineBody:
    """
    Attributes:
        commits (list[str]): The commits to look for an eligible baseline, ordered from the closest to the furthest
            ancestor. The first commit with an eligible baseline wins.
        name (str | Unset): The name of the build to find a baseline for. Default: 'default'.
        mode (FindBaselineBodyMode | Unset): The mode of the build to find a baseline for. Default:
            FindBaselineBodyMode.CI.
    """

    commits: list[str]
    name: str | Unset = "default"
    mode: FindBaselineBodyMode | Unset = FindBaselineBodyMode.CI
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        commits = self.commits

        name = self.name

        mode: str | Unset = UNSET
        if not isinstance(self.mode, Unset):
            mode = self.mode.value

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "commits": commits,
            }
        )
        if name is not UNSET:
            field_dict["name"] = name
        if mode is not UNSET:
            field_dict["mode"] = mode

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        commits = cast(list[str], d.pop("commits"))

        name = d.pop("name", UNSET)

        _mode = d.pop("mode", UNSET)
        mode: FindBaselineBodyMode | Unset
        if isinstance(_mode, Unset):
            mode = UNSET
        else:
            mode = FindBaselineBodyMode(_mode)

        find_baseline_body = cls(
            commits=commits,
            name=name,
            mode=mode,
        )

        find_baseline_body.additional_properties = d
        return find_baseline_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
