# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from enum import Enum


class ListBuildDiffsMetricsPeriod(str, Enum):
    LAST_24_HOURS = "LAST_24_HOURS"
    LAST_30_DAYS = "LAST_30_DAYS"
    LAST_3_DAYS = "LAST_3_DAYS"
    LAST_7_DAYS = "LAST_7_DAYS"
    LAST_90_DAYS = "LAST_90_DAYS"

    def __str__(self) -> str:
        return str(self.value)
