# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.build import Build
    from ..models.page_info import PageInfo


T = TypeVar("T", bound="ListBuildsResponse200")


@_attrs_define
class ListBuildsResponse200:
    """
    Attributes:
        page_info (PageInfo): Page information
        results (list[Build]):
    """

    page_info: PageInfo
    results: list[Build]

    def to_dict(self) -> dict[str, Any]:
        page_info = self.page_info.to_dict()

        results = []
        for results_item_data in self.results:
            results_item = results_item_data.to_dict()
            results.append(results_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "pageInfo": page_info,
                "results": results,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build import Build
        from ..models.page_info import PageInfo

        d = dict(src_dict)
        page_info = PageInfo.from_dict(d.pop("pageInfo"))

        results = []
        _results = d.pop("results")
        for results_item_data in _results:
            results_item = Build.from_dict(results_item_data)

            results.append(results_item)

        list_builds_response_200 = cls(
            page_info=page_info,
            results=results,
        )

        return list_builds_response_200
