# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.me_account import MeAccount
    from ..models.me_github import MeGithub
    from ..models.me_user import MeUser


T = TypeVar("T", bound="Me")


@_attrs_define
class Me:
    """Authenticated user, their accessible accounts, and GitHub linkage

    Attributes:
        user (MeUser): Authenticated user
        accounts (list[MeAccount]):
        github (MeGithub): GitHub linkage status for the authenticated user's account
    """

    user: MeUser
    accounts: list[MeAccount]
    github: MeGithub

    def to_dict(self) -> dict[str, Any]:

        user = self.user.to_dict()

        accounts = []
        for accounts_item_data in self.accounts:
            accounts_item = accounts_item_data.to_dict()
            accounts.append(accounts_item)

        github = self.github.to_dict()

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "user": user,
                "accounts": accounts,
                "github": github,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.me_account import MeAccount
        from ..models.me_github import MeGithub
        from ..models.me_user import MeUser

        d = dict(src_dict)
        user = MeUser.from_dict(d.pop("user"))

        accounts = []
        _accounts = d.pop("accounts")
        for accounts_item_data in _accounts:
            accounts_item = MeAccount.from_dict(accounts_item_data)

            accounts.append(accounts_item)

        github = MeGithub.from_dict(d.pop("github"))

        me = cls(
            user=user,
            accounts=accounts,
            github=github,
        )

        return me
