# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from enum import Enum


class MeAccountType(str, Enum):
    TEAM = "team"
    USER = "user"

    def __str__(self) -> str:
        return str(self.value)
