# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define

from ..models.me_account_type import MeAccountType

T = TypeVar("T", bound="MeAccount")


@_attrs_define
class MeAccount:
    """Account visible to the authenticated user

    Attributes:
        id (str):
        slug (str):
        name (None | str):
        type_ (MeAccountType):
        mcp_access_included (bool):
    """

    id: str
    slug: str
    name: None | str
    type_: MeAccountType
    mcp_access_included: bool

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        slug = self.slug

        name: None | str
        name = self.name

        type_ = self.type_.value

        mcp_access_included = self.mcp_access_included

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "slug": slug,
                "name": name,
                "type": type_,
                "mcpAccessIncluded": mcp_access_included,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        slug = d.pop("slug")

        def _parse_name(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        name = _parse_name(d.pop("name"))

        type_ = MeAccountType(d.pop("type"))

        mcp_access_included = d.pop("mcpAccessIncluded")

        me_account = cls(
            id=id,
            slug=slug,
            name=name,
            type_=type_,
            mcp_access_included=mcp_access_included,
        )

        return me_account
