# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define

T = TypeVar("T", bound="MeGithub")


@_attrs_define
class MeGithub:
    """GitHub linkage status for the authenticated user's account

    Attributes:
        connected (bool):
        login (None | str):
    """

    connected: bool
    login: None | str

    def to_dict(self) -> dict[str, Any]:
        connected = self.connected

        login: None | str
        login = self.login

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "connected": connected,
                "login": login,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        connected = d.pop("connected")

        def _parse_login(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        login = _parse_login(d.pop("login"))

        me_github = cls(
            connected=connected,
            login=login,
        )

        return me_github
