# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="PageInfo")


@_attrs_define
class PageInfo:
    """Page information

    Attributes:
        total (float): Total number of items
        page (float): Current page number
        per_page (float): Number of items per page
    """

    total: float
    page: float
    per_page: float

    def to_dict(self) -> dict[str, Any]:
        total = self.total

        page = self.page

        per_page = self.per_page

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "total": total,
                "page": page,
                "perPage": per_page,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        total = d.pop("total")

        page = d.pop("page")

        per_page = d.pop("perPage")

        page_info = cls(
            total=total,
            page=page,
            per_page=per_page,
        )

        return page_info
