# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="PrContextChangedFile")


@_attrs_define
class PrContextChangedFile:
    """
    Attributes:
        filename (str):
        status (str):
        additions (int):
        deletions (int):
    """

    filename: str
    status: str
    additions: int
    deletions: int

    def to_dict(self) -> dict[str, Any]:
        filename = self.filename

        status = self.status

        additions = self.additions

        deletions = self.deletions

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "filename": filename,
                "status": status,
                "additions": additions,
                "deletions": deletions,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        filename = d.pop("filename")

        status = d.pop("status")

        additions = d.pop("additions")

        deletions = d.pop("deletions")

        pr_context_changed_file = cls(
            filename=filename,
            status=status,
            additions=additions,
            deletions=deletions,
        )

        return pr_context_changed_file
