# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.pr_context_changed_file import PrContextChangedFile


T = TypeVar("T", bound="PrContextType0")


@_attrs_define
class PrContextType0:
    """
    Attributes:
        number (int):
        title (str):
        body (None | str):
        state (str):
        url (str):
        changed_files (list[PrContextChangedFile]):
    """

    number: int
    title: str
    body: None | str
    state: str
    url: str
    changed_files: list[PrContextChangedFile]

    def to_dict(self) -> dict[str, Any]:
        number = self.number

        title = self.title

        body: None | str
        body = self.body

        state = self.state

        url = self.url

        changed_files = []
        for changed_files_item_data in self.changed_files:
            changed_files_item = changed_files_item_data.to_dict()
            changed_files.append(changed_files_item)

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "number": number,
                "title": title,
                "body": body,
                "state": state,
                "url": url,
                "changedFiles": changed_files,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.pr_context_changed_file import PrContextChangedFile

        d = dict(src_dict)
        number = d.pop("number")

        title = d.pop("title")

        def _parse_body(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        body = _parse_body(d.pop("body"))

        state = d.pop("state")

        url = d.pop("url")

        changed_files = []
        _changed_files = d.pop("changedFiles")
        for changed_files_item_data in _changed_files:
            changed_files_item = PrContextChangedFile.from_dict(changed_files_item_data)

            changed_files.append(changed_files_item)

        pr_context_type_0 = cls(
            number=number,
            title=title,
            body=body,
            state=state,
            url=url,
            changed_files=changed_files,
        )

        return pr_context_type_0
