# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.account import Account


T = TypeVar("T", bound="Project")


@_attrs_define
class Project:
    """Project

    Attributes:
        id (str):
        account (Account): Account
        name (str):
        default_base_branch (str):
        has_remote_content_access (bool):
    """

    id: str
    account: Account
    name: str
    default_base_branch: str
    has_remote_content_access: bool

    def to_dict(self) -> dict[str, Any]:

        id = self.id

        account = self.account.to_dict()

        name = self.name

        default_base_branch = self.default_base_branch

        has_remote_content_access = self.has_remote_content_access

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "account": account,
                "name": name,
                "defaultBaseBranch": default_base_branch,
                "hasRemoteContentAccess": has_remote_content_access,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.account import Account

        d = dict(src_dict)
        id = d.pop("id")

        account = Account.from_dict(d.pop("account"))

        name = d.pop("name")

        default_base_branch = d.pop("defaultBaseBranch")

        has_remote_content_access = d.pop("hasRemoteContentAccess")

        project = cls(
            id=id,
            account=account,
            name=name,
            default_base_branch=default_base_branch,
            has_remote_content_access=has_remote_content_access,
        )

        return project
