# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

from ..models.resolve_deployment_domain_response_200_environment import (
    ResolveDeploymentDomainResponse200Environment,
)
from ..models.resolve_deployment_domain_response_200_visibility import (
    ResolveDeploymentDomainResponse200Visibility,
)

T = TypeVar("T", bound="ResolveDeploymentDomainResponse200")


@_attrs_define
class ResolveDeploymentDomainResponse200:
    """
    Attributes:
        deployment_id (str):
        project_id (str):
        environment (ResolveDeploymentDomainResponse200Environment):
        visibility (ResolveDeploymentDomainResponse200Visibility):
    """

    deployment_id: str
    project_id: str
    environment: ResolveDeploymentDomainResponse200Environment
    visibility: ResolveDeploymentDomainResponse200Visibility

    def to_dict(self) -> dict[str, Any]:
        deployment_id = self.deployment_id

        project_id = self.project_id

        environment = self.environment.value

        visibility = self.visibility.value

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "deploymentId": deployment_id,
                "projectId": project_id,
                "environment": environment,
                "visibility": visibility,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        deployment_id = d.pop("deploymentId")

        project_id = d.pop("projectId")

        environment = ResolveDeploymentDomainResponse200Environment(d.pop("environment"))

        visibility = ResolveDeploymentDomainResponse200Visibility(d.pop("visibility"))

        resolve_deployment_domain_response_200 = cls(
            deployment_id=deployment_id,
            project_id=project_id,
            environment=environment,
            visibility=visibility,
        )

        return resolve_deployment_domain_response_200
