# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.screenshot_input_metadata_type_0_color_scheme_type_0 import (
    ScreenshotInputMetadataType0ColorSchemeType0,
)
from ..models.screenshot_input_metadata_type_0_media_type_type_0 import (
    ScreenshotInputMetadataType0MediaTypeType0,
)
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.screenshot_input_metadata_type_0_automation_library import (
        ScreenshotInputMetadataType0AutomationLibrary,
    )
    from ..models.screenshot_input_metadata_type_0_browser_type_0 import (
        ScreenshotInputMetadataType0BrowserType0,
    )
    from ..models.screenshot_input_metadata_type_0_sdk import ScreenshotInputMetadataType0Sdk
    from ..models.screenshot_input_metadata_type_0_story_type_0 import (
        ScreenshotInputMetadataType0StoryType0,
    )
    from ..models.screenshot_input_metadata_type_0_test_type_0 import (
        ScreenshotInputMetadataType0TestType0,
    )
    from ..models.screenshot_input_metadata_type_0_viewport_type_0 import (
        ScreenshotInputMetadataType0ViewportType0,
    )


T = TypeVar("T", bound="ScreenshotInputMetadataType0")


@_attrs_define
class ScreenshotInputMetadataType0:
    """Metadata about a screenshot

    Attributes:
        automation_library (ScreenshotInputMetadataType0AutomationLibrary): The automation library that generated the
            screenshot
        sdk (ScreenshotInputMetadataType0Sdk): The Argos SDK that generated the screenshot
        schema (str | Unset): Ignored. Can be set to get completions, validations and documentation in some editors.
        url (None | str | Unset): The URL of the page that was screenshotted
        preview_url (None | str | Unset): An URL to an accessible preview of the screenshot
        viewport (None | ScreenshotInputMetadataType0ViewportType0 | Unset):
        color_scheme (None | ScreenshotInputMetadataType0ColorSchemeType0 | Unset): The color scheme when the screenshot
            was taken
        media_type (None | ScreenshotInputMetadataType0MediaTypeType0 | Unset): The media type when the screenshot was
            taken
        test (None | ScreenshotInputMetadataType0TestType0 | Unset):
        browser (None | ScreenshotInputMetadataType0BrowserType0 | Unset):
        story (None | ScreenshotInputMetadataType0StoryType0 | Unset): Storybook story metadata
        tags (list[str] | Unset): Tags associated to the screenshot
    """

    automation_library: ScreenshotInputMetadataType0AutomationLibrary
    sdk: ScreenshotInputMetadataType0Sdk
    schema: str | Unset = UNSET
    url: None | str | Unset = UNSET
    preview_url: None | str | Unset = UNSET
    viewport: None | ScreenshotInputMetadataType0ViewportType0 | Unset = UNSET
    color_scheme: None | ScreenshotInputMetadataType0ColorSchemeType0 | Unset = UNSET
    media_type: None | ScreenshotInputMetadataType0MediaTypeType0 | Unset = UNSET
    test: None | ScreenshotInputMetadataType0TestType0 | Unset = UNSET
    browser: None | ScreenshotInputMetadataType0BrowserType0 | Unset = UNSET
    story: None | ScreenshotInputMetadataType0StoryType0 | Unset = UNSET
    tags: list[str] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.screenshot_input_metadata_type_0_browser_type_0 import (
            ScreenshotInputMetadataType0BrowserType0,
        )
        from ..models.screenshot_input_metadata_type_0_story_type_0 import (
            ScreenshotInputMetadataType0StoryType0,
        )
        from ..models.screenshot_input_metadata_type_0_test_type_0 import (
            ScreenshotInputMetadataType0TestType0,
        )
        from ..models.screenshot_input_metadata_type_0_viewport_type_0 import (
            ScreenshotInputMetadataType0ViewportType0,
        )

        automation_library = self.automation_library.to_dict()

        sdk = self.sdk.to_dict()

        schema = self.schema

        url: None | str | Unset
        if isinstance(self.url, Unset):
            url = UNSET
        else:
            url = self.url

        preview_url: None | str | Unset
        if isinstance(self.preview_url, Unset):
            preview_url = UNSET
        else:
            preview_url = self.preview_url

        viewport: dict[str, Any] | None | Unset
        if isinstance(self.viewport, Unset):
            viewport = UNSET
        elif isinstance(self.viewport, ScreenshotInputMetadataType0ViewportType0):
            viewport = self.viewport.to_dict()
        else:
            viewport = self.viewport

        color_scheme: None | str | Unset
        if isinstance(self.color_scheme, Unset):
            color_scheme = UNSET
        elif isinstance(self.color_scheme, ScreenshotInputMetadataType0ColorSchemeType0):
            color_scheme = self.color_scheme.value
        else:
            color_scheme = self.color_scheme

        media_type: None | str | Unset
        if isinstance(self.media_type, Unset):
            media_type = UNSET
        elif isinstance(self.media_type, ScreenshotInputMetadataType0MediaTypeType0):
            media_type = self.media_type.value
        else:
            media_type = self.media_type

        test: dict[str, Any] | None | Unset
        if isinstance(self.test, Unset):
            test = UNSET
        elif isinstance(self.test, ScreenshotInputMetadataType0TestType0):
            test = self.test.to_dict()
        else:
            test = self.test

        browser: dict[str, Any] | None | Unset
        if isinstance(self.browser, Unset):
            browser = UNSET
        elif isinstance(self.browser, ScreenshotInputMetadataType0BrowserType0):
            browser = self.browser.to_dict()
        else:
            browser = self.browser

        story: dict[str, Any] | None | Unset
        if isinstance(self.story, Unset):
            story = UNSET
        elif isinstance(self.story, ScreenshotInputMetadataType0StoryType0):
            story = self.story.to_dict()
        else:
            story = self.story

        tags: list[str] | Unset = UNSET
        if not isinstance(self.tags, Unset):
            tags = self.tags

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "automationLibrary": automation_library,
                "sdk": sdk,
            }
        )
        if schema is not UNSET:
            field_dict["$schema"] = schema
        if url is not UNSET:
            field_dict["url"] = url
        if preview_url is not UNSET:
            field_dict["previewUrl"] = preview_url
        if viewport is not UNSET:
            field_dict["viewport"] = viewport
        if color_scheme is not UNSET:
            field_dict["colorScheme"] = color_scheme
        if media_type is not UNSET:
            field_dict["mediaType"] = media_type
        if test is not UNSET:
            field_dict["test"] = test
        if browser is not UNSET:
            field_dict["browser"] = browser
        if story is not UNSET:
            field_dict["story"] = story
        if tags is not UNSET:
            field_dict["tags"] = tags

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.screenshot_input_metadata_type_0_automation_library import (
            ScreenshotInputMetadataType0AutomationLibrary,
        )
        from ..models.screenshot_input_metadata_type_0_browser_type_0 import (
            ScreenshotInputMetadataType0BrowserType0,
        )
        from ..models.screenshot_input_metadata_type_0_sdk import ScreenshotInputMetadataType0Sdk
        from ..models.screenshot_input_metadata_type_0_story_type_0 import (
            ScreenshotInputMetadataType0StoryType0,
        )
        from ..models.screenshot_input_metadata_type_0_test_type_0 import (
            ScreenshotInputMetadataType0TestType0,
        )
        from ..models.screenshot_input_metadata_type_0_viewport_type_0 import (
            ScreenshotInputMetadataType0ViewportType0,
        )

        d = dict(src_dict)
        automation_library = ScreenshotInputMetadataType0AutomationLibrary.from_dict(
            d.pop("automationLibrary")
        )

        sdk = ScreenshotInputMetadataType0Sdk.from_dict(d.pop("sdk"))

        schema = d.pop("$schema", UNSET)

        def _parse_url(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        url = _parse_url(d.pop("url", UNSET))

        def _parse_preview_url(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        preview_url = _parse_preview_url(d.pop("previewUrl", UNSET))

        def _parse_viewport(
            data: object,
        ) -> None | ScreenshotInputMetadataType0ViewportType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                viewport_type_0 = ScreenshotInputMetadataType0ViewportType0.from_dict(data)

                return viewport_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ScreenshotInputMetadataType0ViewportType0 | Unset, data)

        viewport = _parse_viewport(d.pop("viewport", UNSET))

        def _parse_color_scheme(
            data: object,
        ) -> None | ScreenshotInputMetadataType0ColorSchemeType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                color_scheme_type_0 = ScreenshotInputMetadataType0ColorSchemeType0(data)

                return color_scheme_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ScreenshotInputMetadataType0ColorSchemeType0 | Unset, data)

        color_scheme = _parse_color_scheme(d.pop("colorScheme", UNSET))

        def _parse_media_type(
            data: object,
        ) -> None | ScreenshotInputMetadataType0MediaTypeType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                media_type_type_0 = ScreenshotInputMetadataType0MediaTypeType0(data)

                return media_type_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ScreenshotInputMetadataType0MediaTypeType0 | Unset, data)

        media_type = _parse_media_type(d.pop("mediaType", UNSET))

        def _parse_test(data: object) -> None | ScreenshotInputMetadataType0TestType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                test_type_0 = ScreenshotInputMetadataType0TestType0.from_dict(data)

                return test_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ScreenshotInputMetadataType0TestType0 | Unset, data)

        test = _parse_test(d.pop("test", UNSET))

        def _parse_browser(data: object) -> None | ScreenshotInputMetadataType0BrowserType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                browser_type_0 = ScreenshotInputMetadataType0BrowserType0.from_dict(data)

                return browser_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ScreenshotInputMetadataType0BrowserType0 | Unset, data)

        browser = _parse_browser(d.pop("browser", UNSET))

        def _parse_story(data: object) -> None | ScreenshotInputMetadataType0StoryType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                story_type_0 = ScreenshotInputMetadataType0StoryType0.from_dict(data)

                return story_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ScreenshotInputMetadataType0StoryType0 | Unset, data)

        story = _parse_story(d.pop("story", UNSET))

        tags = cast(list[str], d.pop("tags", UNSET))

        screenshot_input_metadata_type_0 = cls(
            automation_library=automation_library,
            sdk=sdk,
            schema=schema,
            url=url,
            preview_url=preview_url,
            viewport=viewport,
            color_scheme=color_scheme,
            media_type=media_type,
            test=test,
            browser=browser,
            story=story,
            tags=tags,
        )

        screenshot_input_metadata_type_0.additional_properties = d
        return screenshot_input_metadata_type_0

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
