# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="ScreenshotInputMetadataType0StoryType0")


@_attrs_define
class ScreenshotInputMetadataType0StoryType0:
    """Storybook story metadata

    Attributes:
        id (str): Unique ID of the story
        tags (list[str] | Unset): Tags attached to the story
        mode (str | Unset): Story mode
        play (bool | Unset): True if the story has a play function
    """

    id: str
    tags: list[str] | Unset = UNSET
    mode: str | Unset = UNSET
    play: bool | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        tags: list[str] | Unset = UNSET
        if not isinstance(self.tags, Unset):
            tags = self.tags

        mode = self.mode

        play = self.play

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
            }
        )
        if tags is not UNSET:
            field_dict["tags"] = tags
        if mode is not UNSET:
            field_dict["mode"] = mode
        if play is not UNSET:
            field_dict["play"] = play

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        tags = cast(list[str], d.pop("tags", UNSET))

        mode = d.pop("mode", UNSET)

        play = d.pop("play", UNSET)

        screenshot_input_metadata_type_0_story_type_0 = cls(
            id=id,
            tags=tags,
            mode=mode,
            play=play,
        )

        screenshot_input_metadata_type_0_story_type_0.additional_properties = d
        return screenshot_input_metadata_type_0_story_type_0

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
