# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="ScreenshotInputMetadataType0TestType0AnnotationsItemLocation")


@_attrs_define
class ScreenshotInputMetadataType0TestType0AnnotationsItemLocation:
    """The location of the annotation in the source code

    Attributes:
        file (str): The located file
        line (int): The line number in the file
        column (int): The column number in the file
    """

    file: str
    line: int
    column: int
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        file = self.file

        line = self.line

        column = self.column

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "file": file,
                "line": line,
                "column": column,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        file = d.pop("file")

        line = d.pop("line")

        column = d.pop("column")

        screenshot_input_metadata_type_0_test_type_0_annotations_item_location = cls(
            file=file,
            line=line,
            column=column,
        )

        screenshot_input_metadata_type_0_test_type_0_annotations_item_location.additional_properties = d
        return screenshot_input_metadata_type_0_test_type_0_annotations_item_location

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
