# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.screenshot_input_metadata_type_0 import ScreenshotInputMetadataType0


T = TypeVar("T", bound="ScreenshotInput")


@_attrs_define
class ScreenshotInput:
    """Screenshot input

    Attributes:
        key (str):
        name (str):
        base_name (None | str | Unset):
        parent_name (None | str | Unset):
        metadata (None | ScreenshotInputMetadataType0 | Unset):
        pw_trace_key (None | str | Unset):
        threshold (float | None | Unset):
        content_type (str | Unset): Content type of the snapshot file
    """

    key: str
    name: str
    base_name: None | str | Unset = UNSET
    parent_name: None | str | Unset = UNSET
    metadata: None | ScreenshotInputMetadataType0 | Unset = UNSET
    pw_trace_key: None | str | Unset = UNSET
    threshold: float | None | Unset = UNSET
    content_type: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.screenshot_input_metadata_type_0 import ScreenshotInputMetadataType0

        key = self.key

        name = self.name

        base_name: None | str | Unset
        if isinstance(self.base_name, Unset):
            base_name = UNSET
        else:
            base_name = self.base_name

        parent_name: None | str | Unset
        if isinstance(self.parent_name, Unset):
            parent_name = UNSET
        else:
            parent_name = self.parent_name

        metadata: dict[str, Any] | None | Unset
        if isinstance(self.metadata, Unset):
            metadata = UNSET
        elif isinstance(self.metadata, ScreenshotInputMetadataType0):
            metadata = self.metadata.to_dict()
        else:
            metadata = self.metadata

        pw_trace_key: None | str | Unset
        if isinstance(self.pw_trace_key, Unset):
            pw_trace_key = UNSET
        else:
            pw_trace_key = self.pw_trace_key

        threshold: float | None | Unset
        if isinstance(self.threshold, Unset):
            threshold = UNSET
        else:
            threshold = self.threshold

        content_type = self.content_type

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "key": key,
                "name": name,
            }
        )
        if base_name is not UNSET:
            field_dict["baseName"] = base_name
        if parent_name is not UNSET:
            field_dict["parentName"] = parent_name
        if metadata is not UNSET:
            field_dict["metadata"] = metadata
        if pw_trace_key is not UNSET:
            field_dict["pwTraceKey"] = pw_trace_key
        if threshold is not UNSET:
            field_dict["threshold"] = threshold
        if content_type is not UNSET:
            field_dict["contentType"] = content_type

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.screenshot_input_metadata_type_0 import ScreenshotInputMetadataType0

        d = dict(src_dict)
        key = d.pop("key")

        name = d.pop("name")

        def _parse_base_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        base_name = _parse_base_name(d.pop("baseName", UNSET))

        def _parse_parent_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        parent_name = _parse_parent_name(d.pop("parentName", UNSET))

        def _parse_metadata(data: object) -> None | ScreenshotInputMetadataType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                metadata_type_0 = ScreenshotInputMetadataType0.from_dict(data)

                return metadata_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ScreenshotInputMetadataType0 | Unset, data)

        metadata = _parse_metadata(d.pop("metadata", UNSET))

        def _parse_pw_trace_key(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        pw_trace_key = _parse_pw_trace_key(d.pop("pwTraceKey", UNSET))

        def _parse_threshold(data: object) -> float | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(float | None | Unset, data)

        threshold = _parse_threshold(d.pop("threshold", UNSET))

        content_type = d.pop("contentType", UNSET)

        screenshot_input = cls(
            key=key,
            name=name,
            base_name=base_name,
            parent_name=parent_name,
            metadata=metadata,
            pw_trace_key=pw_trace_key,
            threshold=threshold,
            content_type=content_type,
        )

        screenshot_input.additional_properties = d
        return screenshot_input

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
