# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="SnapshotDiffBaseType0MetadataType0ViewportType0")


@_attrs_define
class SnapshotDiffBaseType0MetadataType0ViewportType0:
    """The viewport dimensions when the screenshot was taken

    Attributes:
        width (int): The width of the viewport
        height (int): The height of the viewport
    """

    width: int
    height: int

    def to_dict(self) -> dict[str, Any]:
        width = self.width

        height = self.height

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "width": width,
                "height": height,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        width = d.pop("width")

        height = d.pop("height")

        snapshot_diff_base_type_0_metadata_type_0_viewport_type_0 = cls(
            width=width,
            height=height,
        )

        return snapshot_diff_base_type_0_metadata_type_0_viewport_type_0
