# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.snapshot_diff_head_type_0_metadata_type_0 import (
        SnapshotDiffHeadType0MetadataType0,
    )


T = TypeVar("T", bound="SnapshotDiffHeadType0")


@_attrs_define
class SnapshotDiffHeadType0:
    """Snapshot associated to a diff

    Attributes:
        id (str): Unique identifier of the snapshot
        name (str): Name of the snapshot
        metadata (None | SnapshotDiffHeadType0MetadataType0):
        width (float | None): Width of the screenshot in pixels
        height (float | None): Height of the screenshot in pixels
        url (str): Public URL of the snapshot
        content_type (str): Content type of the snapshot file
    """

    id: str
    name: str
    metadata: None | SnapshotDiffHeadType0MetadataType0
    width: float | None
    height: float | None
    url: str
    content_type: str

    def to_dict(self) -> dict[str, Any]:
        from ..models.snapshot_diff_head_type_0_metadata_type_0 import (
            SnapshotDiffHeadType0MetadataType0,
        )

        id = self.id

        name = self.name

        metadata: dict[str, Any] | None
        if isinstance(self.metadata, SnapshotDiffHeadType0MetadataType0):
            metadata = self.metadata.to_dict()
        else:
            metadata = self.metadata

        width: float | None
        width = self.width

        height: float | None
        height = self.height

        url = self.url

        content_type = self.content_type

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "name": name,
                "metadata": metadata,
                "width": width,
                "height": height,
                "url": url,
                "contentType": content_type,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.snapshot_diff_head_type_0_metadata_type_0 import (
            SnapshotDiffHeadType0MetadataType0,
        )

        d = dict(src_dict)
        id = d.pop("id")

        name = d.pop("name")

        def _parse_metadata(data: object) -> None | SnapshotDiffHeadType0MetadataType0:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                metadata_type_0 = SnapshotDiffHeadType0MetadataType0.from_dict(data)

                return metadata_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | SnapshotDiffHeadType0MetadataType0, data)

        metadata = _parse_metadata(d.pop("metadata"))

        def _parse_width(data: object) -> float | None:
            if data is None:
                return data
            return cast(float | None, data)

        width = _parse_width(d.pop("width"))

        def _parse_height(data: object) -> float | None:
            if data is None:
                return data
            return cast(float | None, data)

        height = _parse_height(d.pop("height"))

        url = d.pop("url")

        content_type = d.pop("contentType")

        snapshot_diff_head_type_0 = cls(
            id=id,
            name=name,
            metadata=metadata,
            width=width,
            height=height,
            url=url,
            content_type=content_type,
        )

        return snapshot_diff_head_type_0
