# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="SnapshotDiffBaseType0MetadataType0BrowserType0")


@_attrs_define
class SnapshotDiffBaseType0MetadataType0BrowserType0:
    """The browser that generated the screenshot

    Attributes:
        name (str): The name of the browser
        version (str): The version of the browser
    """

    name: str
    version: str

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        version = self.version

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "name": name,
                "version": version,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("name")

        version = d.pop("version")

        snapshot_diff_base_type_0_metadata_type_0_browser_type_0 = cls(
            name=name,
            version=version,
        )

        return snapshot_diff_base_type_0_metadata_type_0_browser_type_0
