# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="SnapshotDiffHeadType0MetadataType0TestType0AnnotationsItemLocation")


@_attrs_define
class SnapshotDiffHeadType0MetadataType0TestType0AnnotationsItemLocation:
    """The location of the annotation in the source code

    Attributes:
        file (str): The located file
        line (int): The line number in the file
        column (int): The column number in the file
    """

    file: str
    line: int
    column: int

    def to_dict(self) -> dict[str, Any]:
        file = self.file

        line = self.line

        column = self.column

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "file": file,
                "line": line,
                "column": column,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        file = d.pop("file")

        line = d.pop("line")

        column = d.pop("column")

        snapshot_diff_head_type_0_metadata_type_0_test_type_0_annotations_item_location = cls(
            file=file,
            line=line,
            column=column,
        )

        return snapshot_diff_head_type_0_metadata_type_0_test_type_0_annotations_item_location
