# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from enum import Enum


class SnapshotDiffHeadType0MetadataType0MediaTypeType0(str, Enum):
    PRINT = "print"
    SCREEN = "screen"

    def __str__(self) -> str:
        return str(self.value)
