# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

from ..models.snapshot_diff_status import SnapshotDiffStatus

if TYPE_CHECKING:
    from ..models.snapshot_diff_base_type_0 import SnapshotDiffBaseType0
    from ..models.snapshot_diff_change_type_0 import SnapshotDiffChangeType0
    from ..models.snapshot_diff_head_type_0 import SnapshotDiffHeadType0
    from ..models.test import Test


T = TypeVar("T", bound="SnapshotDiff")


@_attrs_define
class SnapshotDiff:
    """Snapshot diff

    Attributes:
        id (str): Unique identifier of the snapshot diff
        name (str): Name of the snapshot diff
        status (SnapshotDiffStatus): Status of the snapshot diff
        score (float | None): Similarity score between snapshots
        group (None | str): Grouping key for the snapshot diff
        parent_name (None | str): Parent name of the snapshot (usually the story id)
        url (None | str): URL of the diff image
        base (None | SnapshotDiffBaseType0):
        head (None | SnapshotDiffHeadType0):
        test (None | Test):
        change (None | SnapshotDiffChangeType0):
    """

    id: str
    name: str
    status: SnapshotDiffStatus
    score: float | None
    group: None | str
    parent_name: None | str
    url: None | str
    base: None | SnapshotDiffBaseType0
    head: None | SnapshotDiffHeadType0
    test: None | Test
    change: None | SnapshotDiffChangeType0

    def to_dict(self) -> dict[str, Any]:
        from ..models.snapshot_diff_base_type_0 import SnapshotDiffBaseType0
        from ..models.snapshot_diff_change_type_0 import SnapshotDiffChangeType0
        from ..models.snapshot_diff_head_type_0 import SnapshotDiffHeadType0
        from ..models.test import Test

        id = self.id

        name = self.name

        status = self.status.value

        score: float | None
        score = self.score

        group: None | str
        group = self.group

        parent_name: None | str
        parent_name = self.parent_name

        url: None | str
        url = self.url

        base: dict[str, Any] | None
        if isinstance(self.base, SnapshotDiffBaseType0):
            base = self.base.to_dict()
        else:
            base = self.base

        head: dict[str, Any] | None
        if isinstance(self.head, SnapshotDiffHeadType0):
            head = self.head.to_dict()
        else:
            head = self.head

        test: dict[str, Any] | None
        if isinstance(self.test, Test):
            test = self.test.to_dict()
        else:
            test = self.test

        change: dict[str, Any] | None
        if isinstance(self.change, SnapshotDiffChangeType0):
            change = self.change.to_dict()
        else:
            change = self.change

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "name": name,
                "status": status,
                "score": score,
                "group": group,
                "parentName": parent_name,
                "url": url,
                "base": base,
                "head": head,
                "test": test,
                "change": change,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.snapshot_diff_base_type_0 import SnapshotDiffBaseType0
        from ..models.snapshot_diff_change_type_0 import SnapshotDiffChangeType0
        from ..models.snapshot_diff_head_type_0 import SnapshotDiffHeadType0
        from ..models.test import Test

        d = dict(src_dict)
        id = d.pop("id")

        name = d.pop("name")

        status = SnapshotDiffStatus(d.pop("status"))

        def _parse_score(data: object) -> float | None:
            if data is None:
                return data
            return cast(float | None, data)

        score = _parse_score(d.pop("score"))

        def _parse_group(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        group = _parse_group(d.pop("group"))

        def _parse_parent_name(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        parent_name = _parse_parent_name(d.pop("parentName"))

        def _parse_url(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        url = _parse_url(d.pop("url"))

        def _parse_base(data: object) -> None | SnapshotDiffBaseType0:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                base_type_0 = SnapshotDiffBaseType0.from_dict(data)

                return base_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | SnapshotDiffBaseType0, data)

        base = _parse_base(d.pop("base"))

        def _parse_head(data: object) -> None | SnapshotDiffHeadType0:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                head_type_0 = SnapshotDiffHeadType0.from_dict(data)

                return head_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | SnapshotDiffHeadType0, data)

        head = _parse_head(d.pop("head"))

        def _parse_test(data: object) -> None | Test:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                test_type_0 = Test.from_dict(data)

                return test_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Test, data)

        test = _parse_test(d.pop("test"))

        def _parse_change(data: object) -> None | SnapshotDiffChangeType0:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                change_type_0 = SnapshotDiffChangeType0.from_dict(data)

                return change_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | SnapshotDiffChangeType0, data)

        change = _parse_change(d.pop("change"))

        snapshot_diff = cls(
            id=id,
            name=name,
            status=status,
            score=score,
            group=group,
            parent_name=parent_name,
            url=url,
            base=base,
            head=head,
            test=test,
            change=change,
        )

        return snapshot_diff
