# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.snapshot_diff_base_type_0_metadata_type_0_test_type_0_annotations_item_location import (
        SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItemLocation,
    )


T = TypeVar("T", bound="SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem")


@_attrs_define
class SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem:
    """A test annotation

    Attributes:
        type_ (str): The type of annotation
        description (str | Unset): The description of the annotation
        location (SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItemLocation | Unset): The location of the
            annotation in the source code
    """

    type_: str
    description: str | Unset = UNSET
    location: SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItemLocation | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        type_ = self.type_

        description = self.description

        location: dict[str, Any] | Unset = UNSET
        if not isinstance(self.location, Unset):
            location = self.location.to_dict()

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "type": type_,
            }
        )
        if description is not UNSET:
            field_dict["description"] = description
        if location is not UNSET:
            field_dict["location"] = location

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.snapshot_diff_base_type_0_metadata_type_0_test_type_0_annotations_item_location import (
            SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItemLocation,
        )

        d = dict(src_dict)
        type_ = d.pop("type")

        description = d.pop("description", UNSET)

        _location = d.pop("location", UNSET)
        location: SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItemLocation | Unset
        if isinstance(_location, Unset):
            location = UNSET
        else:
            location = SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItemLocation.from_dict(
                _location
            )

        snapshot_diff_base_type_0_metadata_type_0_test_type_0_annotations_item = cls(
            type_=type_,
            description=description,
            location=location,
        )

        return snapshot_diff_base_type_0_metadata_type_0_test_type_0_annotations_item
