# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define

from ..types import UNSET, Unset

T = TypeVar("T", bound="SnapshotDiffHeadType0MetadataType0StoryType0")


@_attrs_define
class SnapshotDiffHeadType0MetadataType0StoryType0:
    """Storybook story metadata

    Attributes:
        id (str): Unique ID of the story
        tags (list[str] | Unset): Tags attached to the story
        mode (str | Unset): Story mode
        play (bool | Unset): True if the story has a play function
    """

    id: str
    tags: list[str] | Unset = UNSET
    mode: str | Unset = UNSET
    play: bool | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        tags: list[str] | Unset = UNSET
        if not isinstance(self.tags, Unset):
            tags = self.tags

        mode = self.mode

        play = self.play

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
            }
        )
        if tags is not UNSET:
            field_dict["tags"] = tags
        if mode is not UNSET:
            field_dict["mode"] = mode
        if play is not UNSET:
            field_dict["play"] = play

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        tags = cast(list[str], d.pop("tags", UNSET))

        mode = d.pop("mode", UNSET)

        play = d.pop("play", UNSET)

        snapshot_diff_head_type_0_metadata_type_0_story_type_0 = cls(
            id=id,
            tags=tags,
            mode=mode,
            play=play,
        )

        return snapshot_diff_head_type_0_metadata_type_0_story_type_0
