# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.snapshot_diff_base_type_0_metadata_type_0_test_type_0_annotations_item import (
        SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem,
    )
    from ..models.snapshot_diff_base_type_0_metadata_type_0_test_type_0_location import (
        SnapshotDiffBaseType0MetadataType0TestType0Location,
    )


T = TypeVar("T", bound="SnapshotDiffBaseType0MetadataType0TestType0")


@_attrs_define
class SnapshotDiffBaseType0MetadataType0TestType0:
    """The test that generated the screenshot

    Attributes:
        title (str): The title of the test
        title_path (list[str]): The path of titles leading to the test
        id (None | str | Unset): The unique identifier of the test
        retries (int | None | Unset): The number of retries for the test
        retry (int | None | Unset): The current retry count
        repeat (int | None | Unset): The repeat count for the test
        location (SnapshotDiffBaseType0MetadataType0TestType0Location | Unset): The location of the test in the source
            code
        annotations (list[SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem] | Unset): Annotations associated
            to the test
        tags (list[str] | Unset): Tags associated to the test
    """

    title: str
    title_path: list[str]
    id: None | str | Unset = UNSET
    retries: int | None | Unset = UNSET
    retry: int | None | Unset = UNSET
    repeat: int | None | Unset = UNSET
    location: SnapshotDiffBaseType0MetadataType0TestType0Location | Unset = UNSET
    annotations: list[SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem] | Unset = UNSET
    tags: list[str] | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        title = self.title

        title_path = self.title_path

        id: None | str | Unset
        if isinstance(self.id, Unset):
            id = UNSET
        else:
            id = self.id

        retries: int | None | Unset
        if isinstance(self.retries, Unset):
            retries = UNSET
        else:
            retries = self.retries

        retry: int | None | Unset
        if isinstance(self.retry, Unset):
            retry = UNSET
        else:
            retry = self.retry

        repeat: int | None | Unset
        if isinstance(self.repeat, Unset):
            repeat = UNSET
        else:
            repeat = self.repeat

        location: dict[str, Any] | Unset = UNSET
        if not isinstance(self.location, Unset):
            location = self.location.to_dict()

        annotations: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.annotations, Unset):
            annotations = []
            for annotations_item_data in self.annotations:
                annotations_item = annotations_item_data.to_dict()
                annotations.append(annotations_item)

        tags: list[str] | Unset = UNSET
        if not isinstance(self.tags, Unset):
            tags = self.tags

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "title": title,
                "titlePath": title_path,
            }
        )
        if id is not UNSET:
            field_dict["id"] = id
        if retries is not UNSET:
            field_dict["retries"] = retries
        if retry is not UNSET:
            field_dict["retry"] = retry
        if repeat is not UNSET:
            field_dict["repeat"] = repeat
        if location is not UNSET:
            field_dict["location"] = location
        if annotations is not UNSET:
            field_dict["annotations"] = annotations
        if tags is not UNSET:
            field_dict["tags"] = tags

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.snapshot_diff_base_type_0_metadata_type_0_test_type_0_annotations_item import (
            SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem,
        )
        from ..models.snapshot_diff_base_type_0_metadata_type_0_test_type_0_location import (
            SnapshotDiffBaseType0MetadataType0TestType0Location,
        )

        d = dict(src_dict)
        title = d.pop("title")

        title_path = cast(list[str], d.pop("titlePath"))

        def _parse_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        id = _parse_id(d.pop("id", UNSET))

        def _parse_retries(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        retries = _parse_retries(d.pop("retries", UNSET))

        def _parse_retry(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        retry = _parse_retry(d.pop("retry", UNSET))

        def _parse_repeat(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        repeat = _parse_repeat(d.pop("repeat", UNSET))

        _location = d.pop("location", UNSET)
        location: SnapshotDiffBaseType0MetadataType0TestType0Location | Unset
        if isinstance(_location, Unset):
            location = UNSET
        else:
            location = SnapshotDiffBaseType0MetadataType0TestType0Location.from_dict(_location)

        _annotations = d.pop("annotations", UNSET)
        annotations: list[SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem] | Unset = (
            UNSET
        )
        if _annotations is not UNSET:
            annotations = []
            for annotations_item_data in _annotations:
                annotations_item = (
                    SnapshotDiffBaseType0MetadataType0TestType0AnnotationsItem.from_dict(
                        annotations_item_data
                    )
                )

                annotations.append(annotations_item)

        tags = cast(list[str], d.pop("tags", UNSET))

        snapshot_diff_base_type_0_metadata_type_0_test_type_0 = cls(
            title=title,
            title_path=title_path,
            id=id,
            retries=retries,
            retry=retry,
            repeat=repeat,
            location=location,
            annotations=annotations,
            tags=tags,
        )

        return snapshot_diff_base_type_0_metadata_type_0_test_type_0
