# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="TestMetrics")


@_attrs_define
class TestMetrics:
    """Flakiness metrics of a test over the requested period.

    Attributes:
        total (float): Number of builds in which this test ran over the metrics period.
        changes (float): Number of times the test changed (produced a diff) over the metrics period.
        unique_changes (float): Number of changes that were seen only once over the metrics period. A high ratio of
            unique changes is a strong flakiness signal.
        stability (float): Ratio of builds without a change, between 0 and 1. `1` means the test never changed.
        consistency (float): How consistent the changes are, between 0 and 1. `1` means changes repeat the same way; a
            low value means changes are erratic.
        flakiness (float): Overall flakiness score between 0 and 1, derived from stability and consistency. `0` means
            stable, `1` means highly flaky.
    """

    total: float
    changes: float
    unique_changes: float
    stability: float
    consistency: float
    flakiness: float

    def to_dict(self) -> dict[str, Any]:
        total = self.total

        changes = self.changes

        unique_changes = self.unique_changes

        stability = self.stability

        consistency = self.consistency

        flakiness = self.flakiness

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "total": total,
                "changes": changes,
                "uniqueChanges": unique_changes,
                "stability": stability,
                "consistency": consistency,
                "flakiness": flakiness,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        total = d.pop("total")

        changes = d.pop("changes")

        unique_changes = d.pop("uniqueChanges")

        stability = d.pop("stability")

        consistency = d.pop("consistency")

        flakiness = d.pop("flakiness")

        test_metrics = cls(
            total=total,
            changes=changes,
            unique_changes=unique_changes,
            stability=stability,
            consistency=consistency,
            flakiness=flakiness,
        )

        return test_metrics
