# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.test_metrics import TestMetrics


T = TypeVar("T", bound="Test")


@_attrs_define
class Test:
    """Test associated to a diff, with flakiness metrics to help decide whether a change is worth reviewing.

    Attributes:
        id (str): Unique identifier of the test
        name (str): Name of the test
        build_name (str): Name of the build the test belongs to
        metrics (TestMetrics): Flakiness metrics of a test over the requested period.
    """

    id: str
    name: str
    build_name: str
    metrics: TestMetrics

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        name = self.name

        build_name = self.build_name

        metrics = self.metrics.to_dict()

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "name": name,
                "buildName": build_name,
                "metrics": metrics,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.test_metrics import TestMetrics

        d = dict(src_dict)
        id = d.pop("id")

        name = d.pop("name")

        build_name = d.pop("buildName")

        metrics = TestMetrics.from_dict(d.pop("metrics"))

        test = cls(
            id=id,
            name=name,
            build_name=build_name,
            metrics=metrics,
        )

        return test
