# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define

if TYPE_CHECKING:
    from ..models.build import Build


T = TypeVar("T", bound="UpdateBuildResponse200")


@_attrs_define
class UpdateBuildResponse200:
    """
    Attributes:
        build (Build): Build
    """

    build: Build

    def to_dict(self) -> dict[str, Any]:

        build = self.build.to_dict()

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "build": build,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build import Build

        d = dict(src_dict)
        build = Build.from_dict(d.pop("build"))

        update_build_response_200 = cls(
            build=build,
        )

        return update_build_response_200
