# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

if TYPE_CHECKING:
    from ..models.update_comment_body_body_type_1 import UpdateCommentBodyBodyType1


T = TypeVar("T", bound="UpdateCommentBody")


@_attrs_define
class UpdateCommentBody:
    """
    Attributes:
        body (str | UpdateCommentBodyBodyType1): Comment content. Either Markdown text or the JSON representation of a
            rich-text document.
    """

    body: str | UpdateCommentBodyBodyType1
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.update_comment_body_body_type_1 import UpdateCommentBodyBodyType1

        body: dict[str, Any] | str
        if isinstance(self.body, UpdateCommentBodyBodyType1):
            body = self.body.to_dict()
        else:
            body = self.body

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "body": body,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.update_comment_body_body_type_1 import UpdateCommentBodyBodyType1

        d = dict(src_dict)

        def _parse_body(data: object) -> str | UpdateCommentBodyBodyType1:
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                body_type_1 = UpdateCommentBodyBodyType1.from_dict(data)

                return body_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(str | UpdateCommentBodyBodyType1, data)

        body = _parse_body(d.pop("body"))

        update_comment_body = cls(
            body=body,
        )

        update_comment_body.additional_properties = d
        return update_comment_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
