# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.build_metadata import BuildMetadata
    from ..models.screenshot_input import ScreenshotInput


T = TypeVar("T", bound="UpdateBuildBody")


@_attrs_define
class UpdateBuildBody:
    """
    Attributes:
        screenshots (list[ScreenshotInput]):
        parallel (bool | None | Unset):
        parallel_total (int | None | Unset):
        parallel_index (int | None | Unset):
        final (bool | None | Unset): Only used for non-parallel builds. Indicates that this is the last request of the
            build, so Argos can finalize it. A build whose screenshots are too large to fit in a single request can split
            them across several sequential requests, leaving `final` falsy on every request but the last. Defaults to
            `true`.
        metadata (BuildMetadata | Unset): Build metadata
    """

    screenshots: list[ScreenshotInput]
    parallel: bool | None | Unset = UNSET
    parallel_total: int | None | Unset = UNSET
    parallel_index: int | None | Unset = UNSET
    final: bool | None | Unset = UNSET
    metadata: BuildMetadata | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        screenshots = []
        for screenshots_item_data in self.screenshots:
            screenshots_item = screenshots_item_data.to_dict()
            screenshots.append(screenshots_item)

        parallel: bool | None | Unset
        if isinstance(self.parallel, Unset):
            parallel = UNSET
        else:
            parallel = self.parallel

        parallel_total: int | None | Unset
        if isinstance(self.parallel_total, Unset):
            parallel_total = UNSET
        else:
            parallel_total = self.parallel_total

        parallel_index: int | None | Unset
        if isinstance(self.parallel_index, Unset):
            parallel_index = UNSET
        else:
            parallel_index = self.parallel_index

        final: bool | None | Unset
        if isinstance(self.final, Unset):
            final = UNSET
        else:
            final = self.final

        metadata: dict[str, Any] | Unset = UNSET
        if not isinstance(self.metadata, Unset):
            metadata = self.metadata.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "screenshots": screenshots,
            }
        )
        if parallel is not UNSET:
            field_dict["parallel"] = parallel
        if parallel_total is not UNSET:
            field_dict["parallelTotal"] = parallel_total
        if parallel_index is not UNSET:
            field_dict["parallelIndex"] = parallel_index
        if final is not UNSET:
            field_dict["final"] = final
        if metadata is not UNSET:
            field_dict["metadata"] = metadata

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.build_metadata import BuildMetadata
        from ..models.screenshot_input import ScreenshotInput

        d = dict(src_dict)
        screenshots = []
        _screenshots = d.pop("screenshots")
        for screenshots_item_data in _screenshots:
            screenshots_item = ScreenshotInput.from_dict(screenshots_item_data)

            screenshots.append(screenshots_item)

        def _parse_parallel(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        parallel = _parse_parallel(d.pop("parallel", UNSET))

        def _parse_parallel_total(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        parallel_total = _parse_parallel_total(d.pop("parallelTotal", UNSET))

        def _parse_parallel_index(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        parallel_index = _parse_parallel_index(d.pop("parallelIndex", UNSET))

        def _parse_final(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        final = _parse_final(d.pop("final", UNSET))

        _metadata = d.pop("metadata", UNSET)
        metadata: BuildMetadata | Unset
        if isinstance(_metadata, Unset):
            metadata = UNSET
        else:
            metadata = BuildMetadata.from_dict(_metadata)

        update_build_body = cls(
            screenshots=screenshots,
            parallel=parallel,
            parallel_total=parallel_total,
            parallel_index=parallel_index,
            final=final,
            metadata=metadata,
        )

        update_build_body.additional_properties = d
        return update_build_body

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
