# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define

T = TypeVar("T", bound="User")


@_attrs_define
class User:
    """A user.

    Attributes:
        id (str):
        slug (str):
        name (None | str):
    """

    id: str
    slug: str
    name: None | str

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        slug = self.slug

        name: None | str
        name = self.name

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "id": id,
                "slug": slug,
                "name": name,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        slug = d.pop("slug")

        def _parse_name(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        name = _parse_name(d.pop("name"))

        user = cls(
            id=id,
            slug=slug,
            name=name,
        )

        return user
