# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.change import Change
from ...models.error import Error
from ...models.ignore_change_metrics_period import IgnoreChangeMetricsPeriod
from ...types import UNSET, Response, Unset


def _get_kwargs(
    owner: str,
    project: str,
    change_id: str,
    *,
    metrics_period: IgnoreChangeMetricsPeriod | Unset = IgnoreChangeMetricsPeriod.LAST_7_DAYS,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    json_metrics_period: str | Unset = UNSET
    if not isinstance(metrics_period, Unset):
        json_metrics_period = metrics_period.value

    params["metricsPeriod"] = json_metrics_period

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/projects/{owner}/{project}/changes/{change_id}/ignore".format(
            owner=quote(str(owner), safe=""),
            project=quote(str(project), safe=""),
            change_id=quote(str(change_id), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Change | Error | None:
    if response.status_code == 200:
        response_200 = Change.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Change | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    owner: str,
    project: str,
    change_id: str,
    *,
    client: AuthenticatedClient,
    metrics_period: IgnoreChangeMetricsPeriod | Unset = IgnoreChangeMetricsPeriod.LAST_7_DAYS,
) -> Response[Change | Error]:
    """Ignore a test change

     Ignore a test change so its diffs no longer require review and are automatically approved on future
    builds. Use it to silence a change that has been identified as flaky.

    Args:
        owner (str):
        project (str):
        change_id (str): Identifier of the change to update, as returned in a diff's `change.id`.
        metrics_period (IgnoreChangeMetricsPeriod | Unset): Period over which the test flakiness
            metrics are computed. Default: IgnoreChangeMetricsPeriod.LAST_7_DAYS.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Change | Error]
    """

    kwargs = _get_kwargs(
        owner=owner,
        project=project,
        change_id=change_id,
        metrics_period=metrics_period,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    owner: str,
    project: str,
    change_id: str,
    *,
    client: AuthenticatedClient,
    metrics_period: IgnoreChangeMetricsPeriod | Unset = IgnoreChangeMetricsPeriod.LAST_7_DAYS,
) -> Change | Error | None:
    """Ignore a test change

     Ignore a test change so its diffs no longer require review and are automatically approved on future
    builds. Use it to silence a change that has been identified as flaky.

    Args:
        owner (str):
        project (str):
        change_id (str): Identifier of the change to update, as returned in a diff's `change.id`.
        metrics_period (IgnoreChangeMetricsPeriod | Unset): Period over which the test flakiness
            metrics are computed. Default: IgnoreChangeMetricsPeriod.LAST_7_DAYS.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Change | Error
    """

    return sync_detailed(
        owner=owner,
        project=project,
        change_id=change_id,
        client=client,
        metrics_period=metrics_period,
    ).parsed


async def asyncio_detailed(
    owner: str,
    project: str,
    change_id: str,
    *,
    client: AuthenticatedClient,
    metrics_period: IgnoreChangeMetricsPeriod | Unset = IgnoreChangeMetricsPeriod.LAST_7_DAYS,
) -> Response[Change | Error]:
    """Ignore a test change

     Ignore a test change so its diffs no longer require review and are automatically approved on future
    builds. Use it to silence a change that has been identified as flaky.

    Args:
        owner (str):
        project (str):
        change_id (str): Identifier of the change to update, as returned in a diff's `change.id`.
        metrics_period (IgnoreChangeMetricsPeriod | Unset): Period over which the test flakiness
            metrics are computed. Default: IgnoreChangeMetricsPeriod.LAST_7_DAYS.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Change | Error]
    """

    kwargs = _get_kwargs(
        owner=owner,
        project=project,
        change_id=change_id,
        metrics_period=metrics_period,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    owner: str,
    project: str,
    change_id: str,
    *,
    client: AuthenticatedClient,
    metrics_period: IgnoreChangeMetricsPeriod | Unset = IgnoreChangeMetricsPeriod.LAST_7_DAYS,
) -> Change | Error | None:
    """Ignore a test change

     Ignore a test change so its diffs no longer require review and are automatically approved on future
    builds. Use it to silence a change that has been identified as flaky.

    Args:
        owner (str):
        project (str):
        change_id (str): Identifier of the change to update, as returned in a diff's `change.id`.
        metrics_period (IgnoreChangeMetricsPeriod | Unset): Period over which the test flakiness
            metrics are computed. Default: IgnoreChangeMetricsPeriod.LAST_7_DAYS.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Change | Error
    """

    return (
        await asyncio_detailed(
            owner=owner,
            project=project,
            change_id=change_id,
            client=client,
            metrics_period=metrics_period,
        )
    ).parsed
