# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.create_build_body import CreateBuildBody
from ...models.create_build_response_201 import CreateBuildResponse201
from ...models.error import Error
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: CreateBuildBody | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/builds",
    }

    if not isinstance(body, Unset):
        _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> CreateBuildResponse201 | Error | None:
    if response.status_code == 201:
        response_201 = CreateBuildResponse201.from_dict(response.json())

        return response_201

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 409:
        response_409 = Error.from_dict(response.json())

        return response_409

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[CreateBuildResponse201 | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateBuildBody | Unset = UNSET,
) -> Response[CreateBuildResponse201 | Error]:
    """Create a build

     Create a build and receive signed upload targets for its screenshots and Playwright traces. The
    response lists, for every file Argos doesn't already have, a secure `postUrl` with `fields` (or a
    legacy `putUrl`) to upload it to. Supports single and parallel builds.

    Args:
        body (CreateBuildBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[CreateBuildResponse201 | Error]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: CreateBuildBody | Unset = UNSET,
) -> CreateBuildResponse201 | Error | None:
    """Create a build

     Create a build and receive signed upload targets for its screenshots and Playwright traces. The
    response lists, for every file Argos doesn't already have, a secure `postUrl` with `fields` (or a
    legacy `putUrl`) to upload it to. Supports single and parallel builds.

    Args:
        body (CreateBuildBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        CreateBuildResponse201 | Error
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateBuildBody | Unset = UNSET,
) -> Response[CreateBuildResponse201 | Error]:
    """Create a build

     Create a build and receive signed upload targets for its screenshots and Playwright traces. The
    response lists, for every file Argos doesn't already have, a secure `postUrl` with `fields` (or a
    legacy `putUrl`) to upload it to. Supports single and parallel builds.

    Args:
        body (CreateBuildBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[CreateBuildResponse201 | Error]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: CreateBuildBody | Unset = UNSET,
) -> CreateBuildResponse201 | Error | None:
    """Create a build

     Create a build and receive signed upload targets for its screenshots and Playwright traces. The
    response lists, for every file Argos doesn't already have, a secure `postUrl` with `fields` (or a
    legacy `putUrl`) to upload it to. Supports single and parallel builds.

    Args:
        body (CreateBuildBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        CreateBuildResponse201 | Error
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
