# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.find_baseline_body import FindBaselineBody
from ...models.find_baseline_response_200 import FindBaselineResponse200
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: FindBaselineBody | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/baseline",
    }

    if not isinstance(body, Unset):
        _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | FindBaselineResponse200 | None:
    if response.status_code == 200:
        response_200 = FindBaselineResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | FindBaselineResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: FindBaselineBody | Unset = UNSET,
) -> Response[Error | FindBaselineResponse200]:
    """Find an eligible baseline from a list of commits

     Find the build eligible to be used as a baseline among a list of commits. Useful when no Git
    provider is connected: the CLI can send the candidate ancestor commits and let Argos pick the
    closest one that has an eligible (complete, valid, approved and not rejected) baseline build.

    Args:
        body (FindBaselineBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | FindBaselineResponse200]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: FindBaselineBody | Unset = UNSET,
) -> Error | FindBaselineResponse200 | None:
    """Find an eligible baseline from a list of commits

     Find the build eligible to be used as a baseline among a list of commits. Useful when no Git
    provider is connected: the CLI can send the candidate ancestor commits and let Argos pick the
    closest one that has an eligible (complete, valid, approved and not rejected) baseline build.

    Args:
        body (FindBaselineBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | FindBaselineResponse200
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: FindBaselineBody | Unset = UNSET,
) -> Response[Error | FindBaselineResponse200]:
    """Find an eligible baseline from a list of commits

     Find the build eligible to be used as a baseline among a list of commits. Useful when no Git
    provider is connected: the CLI can send the candidate ancestor commits and let Argos pick the
    closest one that has an eligible (complete, valid, approved and not rejected) baseline build.

    Args:
        body (FindBaselineBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | FindBaselineResponse200]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: FindBaselineBody | Unset = UNSET,
) -> Error | FindBaselineResponse200 | None:
    """Find an eligible baseline from a list of commits

     Find the build eligible to be used as a baseline among a list of commits. Useful when no Git
    provider is connected: the CLI can send the candidate ancestor commits and let Argos pick the
    closest one that has an eligible (complete, valid, approved and not rejected) baseline build.

    Args:
        body (FindBaselineBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | FindBaselineResponse200
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
