# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.list_builds_response_200 import ListBuildsResponse200
from ...types import UNSET, Response, Unset


def _get_kwargs(
    owner: str,
    project: str,
    *,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    head: str | Unset = UNSET,
    head_sha: str | Unset = UNSET,
    search: str | Unset = UNSET,
    distinct_name: str | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["perPage"] = per_page

    params["page"] = page

    params["head"] = head

    params["headSha"] = head_sha

    params["search"] = search

    params["distinctName"] = distinct_name

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/projects/{owner}/{project}/builds".format(
            owner=quote(str(owner), safe=""),
            project=quote(str(project), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | ListBuildsResponse200 | None:
    if response.status_code == 200:
        response_200 = ListBuildsResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | ListBuildsResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    owner: str,
    project: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    head: str | Unset = UNSET,
    head_sha: str | Unset = UNSET,
    search: str | Unset = UNSET,
    distinct_name: str | Unset = UNSET,
) -> Response[Error | ListBuildsResponse200]:
    """List a project's builds

     List the builds of a project, most recent first. Results are paginated. Use `search` to match builds
    by name, branch or commit, and `distinctName` to return only the latest build per name and commit.

    Args:
        owner (str):
        project (str):
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number
        head (str | Unset):
        head_sha (str | Unset): SHA1 hash
        search (str | Unset): Search builds by name, branch (substring) or commit (prefix).
        distinct_name (str | Unset): Only return the latest builds created, unique by name and
            commit.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ListBuildsResponse200]
    """

    kwargs = _get_kwargs(
        owner=owner,
        project=project,
        per_page=per_page,
        page=page,
        head=head,
        head_sha=head_sha,
        search=search,
        distinct_name=distinct_name,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    owner: str,
    project: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    head: str | Unset = UNSET,
    head_sha: str | Unset = UNSET,
    search: str | Unset = UNSET,
    distinct_name: str | Unset = UNSET,
) -> Error | ListBuildsResponse200 | None:
    """List a project's builds

     List the builds of a project, most recent first. Results are paginated. Use `search` to match builds
    by name, branch or commit, and `distinctName` to return only the latest build per name and commit.

    Args:
        owner (str):
        project (str):
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number
        head (str | Unset):
        head_sha (str | Unset): SHA1 hash
        search (str | Unset): Search builds by name, branch (substring) or commit (prefix).
        distinct_name (str | Unset): Only return the latest builds created, unique by name and
            commit.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ListBuildsResponse200
    """

    return sync_detailed(
        owner=owner,
        project=project,
        client=client,
        per_page=per_page,
        page=page,
        head=head,
        head_sha=head_sha,
        search=search,
        distinct_name=distinct_name,
    ).parsed


async def asyncio_detailed(
    owner: str,
    project: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    head: str | Unset = UNSET,
    head_sha: str | Unset = UNSET,
    search: str | Unset = UNSET,
    distinct_name: str | Unset = UNSET,
) -> Response[Error | ListBuildsResponse200]:
    """List a project's builds

     List the builds of a project, most recent first. Results are paginated. Use `search` to match builds
    by name, branch or commit, and `distinctName` to return only the latest build per name and commit.

    Args:
        owner (str):
        project (str):
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number
        head (str | Unset):
        head_sha (str | Unset): SHA1 hash
        search (str | Unset): Search builds by name, branch (substring) or commit (prefix).
        distinct_name (str | Unset): Only return the latest builds created, unique by name and
            commit.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ListBuildsResponse200]
    """

    kwargs = _get_kwargs(
        owner=owner,
        project=project,
        per_page=per_page,
        page=page,
        head=head,
        head_sha=head_sha,
        search=search,
        distinct_name=distinct_name,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    owner: str,
    project: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    head: str | Unset = UNSET,
    head_sha: str | Unset = UNSET,
    search: str | Unset = UNSET,
    distinct_name: str | Unset = UNSET,
) -> Error | ListBuildsResponse200 | None:
    """List a project's builds

     List the builds of a project, most recent first. Results are paginated. Use `search` to match builds
    by name, branch or commit, and `distinctName` to return only the latest build per name and commit.

    Args:
        owner (str):
        project (str):
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number
        head (str | Unset):
        head_sha (str | Unset): SHA1 hash
        search (str | Unset): Search builds by name, branch (substring) or commit (prefix).
        distinct_name (str | Unset): Only return the latest builds created, unique by name and
            commit.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ListBuildsResponse200
    """

    return (
        await asyncio_detailed(
            owner=owner,
            project=project,
            client=client,
            per_page=per_page,
            page=page,
            head=head,
            head_sha=head_sha,
            search=search,
            distinct_name=distinct_name,
        )
    ).parsed
