# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.list_build_diffs_metrics_period import ListBuildDiffsMetricsPeriod
from ...models.list_build_diffs_response_200 import ListBuildDiffsResponse200
from ...types import UNSET, Response, Unset


def _get_kwargs(
    owner: str,
    project: str,
    build_number: str,
    *,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    needs_review: str | Unset = UNSET,
    metrics_period: ListBuildDiffsMetricsPeriod | Unset = ListBuildDiffsMetricsPeriod.LAST_7_DAYS,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["perPage"] = per_page

    params["page"] = page

    params["needsReview"] = needs_review

    json_metrics_period: str | Unset = UNSET
    if not isinstance(metrics_period, Unset):
        json_metrics_period = metrics_period.value

    params["metricsPeriod"] = json_metrics_period

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/projects/{owner}/{project}/builds/{build_number}/diffs".format(
            owner=quote(str(owner), safe=""),
            project=quote(str(project), safe=""),
            build_number=quote(str(build_number), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | ListBuildDiffsResponse200 | None:
    if response.status_code == 200:
        response_200 = ListBuildDiffsResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | ListBuildDiffsResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    owner: str,
    project: str,
    build_number: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    needs_review: str | Unset = UNSET,
    metrics_period: ListBuildDiffsMetricsPeriod | Unset = ListBuildDiffsMetricsPeriod.LAST_7_DAYS,
) -> Response[Error | ListBuildDiffsResponse200]:
    """List a build's screenshot diffs

     List the screenshot diffs of a build, with pagination. Each diff compares a baseline screenshot to
    the one captured by the build. Each diff also carries its test's flakiness metrics and, when it is a
    change, its ignore state and occurrence count — so you can tell whether a change is worth reviewing
    or is just a flaky one. Use `needsReview` to return only the diffs that require review.

    Args:
        owner (str):
        project (str):
        build_number (str): The build number Example: 42.
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number
        needs_review (str | Unset): Only return diffs that require review. Matches `changed`,
            `added`, and `removed`, except `removed` is excluded for subset builds.
        metrics_period (ListBuildDiffsMetricsPeriod | Unset): Period over which the test flakiness
            metrics are computed. Default: ListBuildDiffsMetricsPeriod.LAST_7_DAYS.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ListBuildDiffsResponse200]
    """

    kwargs = _get_kwargs(
        owner=owner,
        project=project,
        build_number=build_number,
        per_page=per_page,
        page=page,
        needs_review=needs_review,
        metrics_period=metrics_period,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    owner: str,
    project: str,
    build_number: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    needs_review: str | Unset = UNSET,
    metrics_period: ListBuildDiffsMetricsPeriod | Unset = ListBuildDiffsMetricsPeriod.LAST_7_DAYS,
) -> Error | ListBuildDiffsResponse200 | None:
    """List a build's screenshot diffs

     List the screenshot diffs of a build, with pagination. Each diff compares a baseline screenshot to
    the one captured by the build. Each diff also carries its test's flakiness metrics and, when it is a
    change, its ignore state and occurrence count — so you can tell whether a change is worth reviewing
    or is just a flaky one. Use `needsReview` to return only the diffs that require review.

    Args:
        owner (str):
        project (str):
        build_number (str): The build number Example: 42.
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number
        needs_review (str | Unset): Only return diffs that require review. Matches `changed`,
            `added`, and `removed`, except `removed` is excluded for subset builds.
        metrics_period (ListBuildDiffsMetricsPeriod | Unset): Period over which the test flakiness
            metrics are computed. Default: ListBuildDiffsMetricsPeriod.LAST_7_DAYS.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ListBuildDiffsResponse200
    """

    return sync_detailed(
        owner=owner,
        project=project,
        build_number=build_number,
        client=client,
        per_page=per_page,
        page=page,
        needs_review=needs_review,
        metrics_period=metrics_period,
    ).parsed


async def asyncio_detailed(
    owner: str,
    project: str,
    build_number: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    needs_review: str | Unset = UNSET,
    metrics_period: ListBuildDiffsMetricsPeriod | Unset = ListBuildDiffsMetricsPeriod.LAST_7_DAYS,
) -> Response[Error | ListBuildDiffsResponse200]:
    """List a build's screenshot diffs

     List the screenshot diffs of a build, with pagination. Each diff compares a baseline screenshot to
    the one captured by the build. Each diff also carries its test's flakiness metrics and, when it is a
    change, its ignore state and occurrence count — so you can tell whether a change is worth reviewing
    or is just a flaky one. Use `needsReview` to return only the diffs that require review.

    Args:
        owner (str):
        project (str):
        build_number (str): The build number Example: 42.
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number
        needs_review (str | Unset): Only return diffs that require review. Matches `changed`,
            `added`, and `removed`, except `removed` is excluded for subset builds.
        metrics_period (ListBuildDiffsMetricsPeriod | Unset): Period over which the test flakiness
            metrics are computed. Default: ListBuildDiffsMetricsPeriod.LAST_7_DAYS.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ListBuildDiffsResponse200]
    """

    kwargs = _get_kwargs(
        owner=owner,
        project=project,
        build_number=build_number,
        per_page=per_page,
        page=page,
        needs_review=needs_review,
        metrics_period=metrics_period,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    owner: str,
    project: str,
    build_number: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
    needs_review: str | Unset = UNSET,
    metrics_period: ListBuildDiffsMetricsPeriod | Unset = ListBuildDiffsMetricsPeriod.LAST_7_DAYS,
) -> Error | ListBuildDiffsResponse200 | None:
    """List a build's screenshot diffs

     List the screenshot diffs of a build, with pagination. Each diff compares a baseline screenshot to
    the one captured by the build. Each diff also carries its test's flakiness metrics and, when it is a
    change, its ignore state and occurrence count — so you can tell whether a change is worth reviewing
    or is just a flaky one. Use `needsReview` to return only the diffs that require review.

    Args:
        owner (str):
        project (str):
        build_number (str): The build number Example: 42.
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number
        needs_review (str | Unset): Only return diffs that require review. Matches `changed`,
            `added`, and `removed`, except `removed` is excluded for subset builds.
        metrics_period (ListBuildDiffsMetricsPeriod | Unset): Period over which the test flakiness
            metrics are computed. Default: ListBuildDiffsMetricsPeriod.LAST_7_DAYS.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ListBuildDiffsResponse200
    """

    return (
        await asyncio_detailed(
            owner=owner,
            project=project,
            build_number=build_number,
            client=client,
            per_page=per_page,
            page=page,
            needs_review=needs_review,
            metrics_period=metrics_period,
        )
    ).parsed
