# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.update_build_body import UpdateBuildBody
from ...models.update_build_response_200 import UpdateBuildResponse200
from ...types import UNSET, Response, Unset


def _get_kwargs(
    build_id: str,
    *,
    body: UpdateBuildBody | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "put",
        "url": "/builds/{build_id}".format(
            build_id=quote(str(build_id), safe=""),
        ),
    }

    if not isinstance(body, Unset):
        _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | UpdateBuildResponse200 | None:
    if response.status_code == 200:
        response_200 = UpdateBuildResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Error.from_dict(response.json())

        return response_409

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | UpdateBuildResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    build_id: str,
    *,
    client: AuthenticatedClient,
    body: UpdateBuildBody | Unset = UNSET,
) -> Response[Error | UpdateBuildResponse200]:
    """Update a build

     Add screenshots to an existing build and update its metadata. Used to push the screenshots of a
    parallel shard, identified by `parallelIndex` and `parallelTotal`.

    Args:
        build_id (str): A unique identifier for the build Example: 12345.
        body (UpdateBuildBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | UpdateBuildResponse200]
    """

    kwargs = _get_kwargs(
        build_id=build_id,
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    build_id: str,
    *,
    client: AuthenticatedClient,
    body: UpdateBuildBody | Unset = UNSET,
) -> Error | UpdateBuildResponse200 | None:
    """Update a build

     Add screenshots to an existing build and update its metadata. Used to push the screenshots of a
    parallel shard, identified by `parallelIndex` and `parallelTotal`.

    Args:
        build_id (str): A unique identifier for the build Example: 12345.
        body (UpdateBuildBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | UpdateBuildResponse200
    """

    return sync_detailed(
        build_id=build_id,
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    build_id: str,
    *,
    client: AuthenticatedClient,
    body: UpdateBuildBody | Unset = UNSET,
) -> Response[Error | UpdateBuildResponse200]:
    """Update a build

     Add screenshots to an existing build and update its metadata. Used to push the screenshots of a
    parallel shard, identified by `parallelIndex` and `parallelTotal`.

    Args:
        build_id (str): A unique identifier for the build Example: 12345.
        body (UpdateBuildBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | UpdateBuildResponse200]
    """

    kwargs = _get_kwargs(
        build_id=build_id,
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    build_id: str,
    *,
    client: AuthenticatedClient,
    body: UpdateBuildBody | Unset = UNSET,
) -> Error | UpdateBuildResponse200 | None:
    """Update a build

     Add screenshots to an existing build and update its metadata. Used to push the screenshots of a
    parallel shard, identified by `parallelIndex` and `parallelTotal`.

    Args:
        build_id (str): A unique identifier for the build Example: 12345.
        body (UpdateBuildBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | UpdateBuildResponse200
    """

    return (
        await asyncio_detailed(
            build_id=build_id,
            client=client,
            body=body,
        )
    ).parsed
