# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.pr_context_type_0 import PrContextType0
from ...types import Response


def _get_kwargs(
    owner: str,
    repo: str,
    sha: str,
) -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/repos/{owner}/{repo}/commits/{sha}/pulls".format(
            owner=quote(str(owner), safe=""),
            repo=quote(str(repo), safe=""),
            sha=quote(str(sha), safe=""),
        ),
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | None | PrContextType0 | None:
    if response.status_code == 200:

        def _parse_response_200(data: object) -> None | PrContextType0:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                componentsschemas_pr_context_type_0 = PrContextType0.from_dict(data)

                return componentsschemas_pr_context_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | PrContextType0, data)

        response_200 = _parse_response_200(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | None | PrContextType0]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    owner: str,
    repo: str,
    sha: str,
    *,
    client: AuthenticatedClient,
) -> Response[Error | None | PrContextType0]:
    """
    Args:
        owner (str):
        repo (str):
        sha (str): SHA1 hash

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | None | PrContextType0]
    """

    kwargs = _get_kwargs(
        owner=owner,
        repo=repo,
        sha=sha,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    owner: str,
    repo: str,
    sha: str,
    *,
    client: AuthenticatedClient,
) -> Error | None | PrContextType0 | None:
    """
    Args:
        owner (str):
        repo (str):
        sha (str): SHA1 hash

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | None | PrContextType0
    """

    return sync_detailed(
        owner=owner,
        repo=repo,
        sha=sha,
        client=client,
    ).parsed


async def asyncio_detailed(
    owner: str,
    repo: str,
    sha: str,
    *,
    client: AuthenticatedClient,
) -> Response[Error | None | PrContextType0]:
    """
    Args:
        owner (str):
        repo (str):
        sha (str): SHA1 hash

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | None | PrContextType0]
    """

    kwargs = _get_kwargs(
        owner=owner,
        repo=repo,
        sha=sha,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    owner: str,
    repo: str,
    sha: str,
    *,
    client: AuthenticatedClient,
) -> Error | None | PrContextType0 | None:
    """
    Args:
        owner (str):
        repo (str):
        sha (str): SHA1 hash

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | None | PrContextType0
    """

    return (
        await asyncio_detailed(
            owner=owner,
            repo=repo,
            sha=sha,
            client=client,
        )
    ).parsed
