# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.create_deployment_body import CreateDeploymentBody
from ...models.create_deployment_response_201 import CreateDeploymentResponse201
from ...models.error import Error
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: CreateDeploymentBody | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/deployments",
    }

    if not isinstance(body, Unset):
        _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> CreateDeploymentResponse201 | Error | None:
    if response.status_code == 201:
        response_201 = CreateDeploymentResponse201.from_dict(response.json())

        return response_201

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[CreateDeploymentResponse201 | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateDeploymentBody | Unset = UNSET,
) -> Response[CreateDeploymentResponse201 | Error]:
    """Create a deployment

     Create a deployment and receive signed upload URLs for the files Argos doesn't already store. Files
    already present (matched by content hash) are reused and omitted from `uploadFiles`. The environment
    is inferred from the branch when omitted.

    Args:
        body (CreateDeploymentBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[CreateDeploymentResponse201 | Error]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: CreateDeploymentBody | Unset = UNSET,
) -> CreateDeploymentResponse201 | Error | None:
    """Create a deployment

     Create a deployment and receive signed upload URLs for the files Argos doesn't already store. Files
    already present (matched by content hash) are reused and omitted from `uploadFiles`. The environment
    is inferred from the branch when omitted.

    Args:
        body (CreateDeploymentBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        CreateDeploymentResponse201 | Error
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateDeploymentBody | Unset = UNSET,
) -> Response[CreateDeploymentResponse201 | Error]:
    """Create a deployment

     Create a deployment and receive signed upload URLs for the files Argos doesn't already store. Files
    already present (matched by content hash) are reused and omitted from `uploadFiles`. The environment
    is inferred from the branch when omitted.

    Args:
        body (CreateDeploymentBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[CreateDeploymentResponse201 | Error]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: CreateDeploymentBody | Unset = UNSET,
) -> CreateDeploymentResponse201 | Error | None:
    """Create a deployment

     Create a deployment and receive signed upload URLs for the files Argos doesn't already store. Files
    already present (matched by content hash) are reused and omitted from `uploadFiles`. The environment
    is inferred from the branch when omitted.

    Args:
        body (CreateDeploymentBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        CreateDeploymentResponse201 | Error
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
