# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.
from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.finalize_deployment_response_200 import FinalizeDeploymentResponse200
from ...types import Response


def _get_kwargs(
    deployment_id: str,
) -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/deployments/{deployment_id}/finalize".format(
            deployment_id=quote(str(deployment_id), safe=""),
        ),
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | FinalizeDeploymentResponse200 | None:
    if response.status_code == 200:
        response_200 = FinalizeDeploymentResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | FinalizeDeploymentResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    deployment_id: str,
    *,
    client: AuthenticatedClient,
) -> Response[Error | FinalizeDeploymentResponse200]:
    """Finalize a deployment

     Mark a deployment as ready once all of its files have been uploaded. Argos assigns the deployment's
    aliases and starts serving it.

    Args:
        deployment_id (str): The deployment ID

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | FinalizeDeploymentResponse200]
    """

    kwargs = _get_kwargs(
        deployment_id=deployment_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    deployment_id: str,
    *,
    client: AuthenticatedClient,
) -> Error | FinalizeDeploymentResponse200 | None:
    """Finalize a deployment

     Mark a deployment as ready once all of its files have been uploaded. Argos assigns the deployment's
    aliases and starts serving it.

    Args:
        deployment_id (str): The deployment ID

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | FinalizeDeploymentResponse200
    """

    return sync_detailed(
        deployment_id=deployment_id,
        client=client,
    ).parsed


async def asyncio_detailed(
    deployment_id: str,
    *,
    client: AuthenticatedClient,
) -> Response[Error | FinalizeDeploymentResponse200]:
    """Finalize a deployment

     Mark a deployment as ready once all of its files have been uploaded. Argos assigns the deployment's
    aliases and starts serving it.

    Args:
        deployment_id (str): The deployment ID

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | FinalizeDeploymentResponse200]
    """

    kwargs = _get_kwargs(
        deployment_id=deployment_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    deployment_id: str,
    *,
    client: AuthenticatedClient,
) -> Error | FinalizeDeploymentResponse200 | None:
    """Finalize a deployment

     Mark a deployment as ready once all of its files have been uploaded. Argos assigns the deployment's
    aliases and starts serving it.

    Args:
        deployment_id (str): The deployment ID

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | FinalizeDeploymentResponse200
    """

    return (
        await asyncio_detailed(
            deployment_id=deployment_id,
            client=client,
        )
    ).parsed
