#!/usr/bin/env python3
"""Regenerate ``src/snapvisor/_generated`` from the Snapvisor OpenAPI document.

This is the single source of truth for the SDK's API coverage: every operation
the backend publishes becomes an importable, fully typed Python callable. The
handwritten layer (``upload.py``, ``client.py``, ``resources/``) sits *on top* of
this tree and is never generated.

Usage::

    python scripts/regen.py                 # fetch the live spec, regenerate
    python scripts/regen.py --offline       # regenerate from the vendored spec
    python scripts/regen.py --check         # fail if regeneration changes anything

The live document declares ``openapi: 3.2.0`` (emitted by ``zod-openapi``), while
``openapi-python-client`` supports 3.1.x. The document uses no 3.2-only
constructs, so the vendored snapshot is normalised to ``3.1.0``; that rewrite is
the *only* edit applied to the spec and is asserted by the drift check.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_URL = "https://api.snapvisor.io/v2/openapi.yaml"
VENDORED_SPEC = REPO_ROOT / "openapi.yaml"
GEN_CONFIG = REPO_ROOT / "gen-config.yaml"
TARGET = REPO_ROOT / "src" / "snapvisor" / "_generated"
REGISTRY = REPO_ROOT / "src" / "snapvisor" / "_operations.py"

# The generated tree carries this banner so no one mistakes it for handwritten code.
BANNER = (
    "# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.\n"
    "# Any manual change is erased on the next regeneration and will fail the\n"
    "# `spec-drift` CI job.\n"
)

# Maps an OpenAPI tag to the resource-namespace attribute on the Snapvisor facade.
TAG_TO_NAMESPACE = {
    "Builds": "builds",
    "Comments": "comments",
    "Deployments": "deployments",
    "Projects": "projects",
    "Reviews": "reviews",
    "Authentication": "auth",
    "Changes": "changes",
    "Analytics": "analytics",
    "Users": "users",
    "Repositories": "repos",
}
DEFAULT_NAMESPACE = "misc"

# The document leaves a handful of operations untagged; give them a home rather
# than letting them fall into `misc`.
OPERATION_NAMESPACE_OVERRIDES = {
    "getRepoCommitPulls": "repos",
}


def fetch_spec(offline: bool) -> str:
    if offline:
        return VENDORED_SPEC.read_text(encoding="utf-8")
    # An explicit User-Agent is required: the edge in front of api.snapvisor.io
    # answers 403 to the default `Python-urllib/3.x`, which is how this job first
    # failed on a GitHub-hosted runner.
    request = urllib.request.Request(  # noqa: S310
        SPEC_URL, headers={"User-Agent": "snapvisor-python-regen", "Accept": "application/yaml"}
    )
    with urllib.request.urlopen(request, timeout=60) as response:  # noqa: S310
        return response.read().decode("utf-8")


def normalise_spec(raw: str) -> str:
    """Pin the document to OpenAPI 3.1.0 (see module docstring)."""
    normalised, count = re.subn(
        r"^openapi: ['\"]?3\.2\.\d+['\"]?", "openapi: 3.1.0", raw, count=1, flags=re.MULTILINE
    )
    if count == 0 and not re.match(r"^openapi: ['\"]?3\.1\.", raw):
        raise SystemExit(
            "Unexpected OpenAPI version header; refusing to regenerate. "
            f"First line was: {raw.splitlines()[0]!r}"
        )
    return normalised


def load_spec(text: str) -> dict:
    try:
        import yaml
    except ImportError as error:  # pragma: no cover - dev tooling
        raise SystemExit("PyYAML is required: pip install -e '.[dev]'") from error
    data = yaml.safe_load(text)
    if not isinstance(data, dict):
        raise SystemExit("OpenAPI document did not parse to a mapping.")
    return data


def run_generator(spec_path: Path, output_root: Path) -> Path:
    subprocess.run(
        [
            sys.executable,
            "-m",
            "openapi_python_client",
            "generate",
            "--path",
            str(spec_path),
            "--config",
            str(GEN_CONFIG),
            "--output-path",
            str(output_root),
            "--overwrite",
        ],
        check=True,
        cwd=REPO_ROOT,
    )
    package = output_root / "_generated"
    if not package.is_dir():
        raise SystemExit(f"Generator did not produce {package}")
    return package


def install_package(package: Path) -> None:
    if TARGET.exists():
        shutil.rmtree(TARGET)
    shutil.copytree(package, TARGET)
    for path in sorted(TARGET.rglob("*.py")):
        # Normalise leading blank lines before stamping the banner so the
        # installed tree cannot vary with how the generator emitted the file.
        text = path.read_text(encoding="utf-8").lstrip("\n")
        path.write_text(BANNER + "\n" + text, encoding="utf-8", newline="\n")


def canonical_route(method: str, path: str) -> tuple[str, str]:
    """Key a route by method + path shape, ignoring placeholder *names*.

    The generator renames path parameters to snake_case inside the URL template
    (``{accountSlug}`` becomes ``{account_slug}``), so the raw strings do not
    compare equal to the spec's.
    """
    return method.lower(), re.sub(r"\{[^}]+\}", "{}", path)


def module_index() -> dict[tuple[str, str], str]:
    """Map a canonical route to the generated module's dotted name.

    Derived from the generated source rather than from the generator's
    snake_case algorithm, so a change in that algorithm can never silently
    mis-key the registry.
    """
    index: dict[tuple[str, str], str] = {}
    api_root = TARGET / "api"
    for path in sorted(api_root.rglob("*.py")):
        if path.name == "__init__.py":
            continue
        source = path.read_text(encoding="utf-8")
        method = re.search(r'"method":\s*"([a-z]+)"', source)
        url = re.search(r'"url":\s*"([^"]+)"', source)
        if not method or not url:
            raise SystemExit(f"Could not read method/url out of generated module {path}")
        relative = path.relative_to(TARGET).with_suffix("")
        dotted = "snapvisor._generated." + ".".join(relative.parts)
        key = canonical_route(method.group(1), url.group(1))
        if key in index:
            raise SystemExit(
                f"Two generated modules claim the same route {key}: {index[key]}, {dotted}"
            )
        index[key] = dotted
    return index


def write_registry(spec: dict) -> None:
    index = module_index()
    rows: list[dict[str, str]] = []
    for path, item in spec["paths"].items():
        for method, operation in item.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue
            operation_id = operation.get("operationId")
            if not operation_id:
                raise SystemExit(f"Operation {method.upper()} {path} has no operationId")
            module = index.get(canonical_route(method, path))
            if module is None:
                raise SystemExit(
                    f"No generated module for {method.upper()} {path} ({operation_id})"
                )
            tags = operation.get("tags") or []
            tag = tags[0] if tags else ""
            rows.append(
                {
                    "operation_id": operation_id,
                    "method": method.upper(),
                    "path": path,
                    "tag": tag,
                    "namespace": OPERATION_NAMESPACE_OVERRIDES.get(
                        operation_id, TAG_TO_NAMESPACE.get(tag, DEFAULT_NAMESPACE)
                    ),
                    "module": module,
                    "python_name": module.rsplit(".", 1)[1],
                }
            )
    rows.sort(key=lambda row: row["operation_id"])

    lines = [
        '"""Registry of every operation published by the Snapvisor OpenAPI document.',
        "",
        "GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.",
        "",
        "The registry is what makes SDK coverage *structural*: resource namespaces are",
        "built from it at import time, so a new backend operation becomes reachable by",
        "regenerating rather than by hand-writing a call site.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class OperationInfo:",
        '    """One operation from the OpenAPI document, and where its code lives."""',
        "",
        "    operation_id: str",
        "    method: str",
        "    path: str",
        "    tag: str",
        "    namespace: str",
        "    module: str",
        "    python_name: str",
        "",
        "",
        "OPERATIONS: dict[str, OperationInfo] = {",
    ]
    for row in rows:
        lines.append(f"    {json.dumps(row['operation_id'])}: OperationInfo(")
        for field in (
            "operation_id",
            "method",
            "path",
            "tag",
            "namespace",
            "module",
            "python_name",
        ):
            lines.append(f"        {field}={json.dumps(row[field])},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    namespaces = sorted({row["namespace"] for row in rows})
    lines.append(f"NAMESPACES: tuple[str, ...] = {tuple(namespaces)!r}")
    lines.append("")
    REGISTRY.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def format_tree() -> None:
    """Reformat the installed tree with *this repo's* ruff config.

    Format first so `ruff check` never reports line lengths that formatting is
    about to fix, then apply safe fixes, then format again so any fix is itself
    formatted. Ruff is invoked through ``python -m`` so the result never depends
    on which ruff happens to be on PATH.
    """
    ruff = [sys.executable, "-m", "ruff"]
    for args in (
        [*ruff, "format", "--quiet", str(TARGET), str(REGISTRY)],
        [*ruff, "check", "--fix", "--quiet", str(TARGET), str(REGISTRY)],
        [*ruff, "format", "--quiet", str(TARGET), str(REGISTRY)],
    ):
        subprocess.run(args, check=False, cwd=REPO_ROOT)


def git_is_dirty() -> bool:
    paths = [str(TARGET), str(REGISTRY), str(VENDORED_SPEC)]
    result = subprocess.run(
        ["git", "status", "--porcelain", "--", *paths],
        check=True,
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    if not result.stdout.strip():
        return False
    # Print the diff, not just the file list: a drift failure in CI has to be
    # diagnosable from the log alone.
    diff = subprocess.run(
        ["git", "diff", "--", *paths],
        check=False,
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    sys.stderr.write(
        "Generated client is out of date with the live OpenAPI document.\n"
        "Run `python scripts/regen.py` and commit the result.\n\n"
        + result.stdout
        + "\n"
        + diff.stdout[:20000]
    )
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--offline", action="store_true", help="use the vendored openapi.yaml")
    parser.add_argument(
        "--check", action="store_true", help="fail if regeneration produces any change"
    )
    args = parser.parse_args()

    raw = fetch_spec(offline=args.offline)
    normalised = normalise_spec(raw)
    VENDORED_SPEC.write_text(normalised, encoding="utf-8", newline="\n")
    spec = load_spec(normalised)

    with tempfile.TemporaryDirectory() as tmp:
        package = run_generator(VENDORED_SPEC, Path(tmp))
        install_package(package)

    write_registry(spec)
    format_tree()

    operations = len(
        [
            operation
            for item in spec["paths"].values()
            for method, operation in item.items()
            if method in ("get", "post", "put", "patch", "delete")
        ]
    )
    print(f"Regenerated {operations} operations into {TARGET.relative_to(REPO_ROOT)}")

    if args.check and git_is_dirty():
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
