# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.list_projects_response_200 import ListProjectsResponse200
from ...types import UNSET, Response, Unset


def _get_kwargs(
    account_slug: str,
    *,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["perPage"] = per_page

    params["page"] = page

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/accounts/{account_slug}/projects".format(
            account_slug=quote(str(account_slug), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | ListProjectsResponse200 | None:
    if response.status_code == 200:
        response_200 = ListProjectsResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | ListProjectsResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    account_slug: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
) -> Response[Error | ListProjectsResponse200]:
    """List an account's projects

     List the projects of an account that are visible to the authenticated user, most recently active
    first. Results are paginated. The token must be scoped to the account.

    Args:
        account_slug (str): Slug of the account to list projects for.
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ListProjectsResponse200]
    """

    kwargs = _get_kwargs(
        account_slug=account_slug,
        per_page=per_page,
        page=page,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    account_slug: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
) -> Error | ListProjectsResponse200 | None:
    """List an account's projects

     List the projects of an account that are visible to the authenticated user, most recently active
    first. Results are paginated. The token must be scoped to the account.

    Args:
        account_slug (str): Slug of the account to list projects for.
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ListProjectsResponse200
    """

    return sync_detailed(
        account_slug=account_slug,
        client=client,
        per_page=per_page,
        page=page,
    ).parsed


async def asyncio_detailed(
    account_slug: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
) -> Response[Error | ListProjectsResponse200]:
    """List an account's projects

     List the projects of an account that are visible to the authenticated user, most recently active
    first. Results are paginated. The token must be scoped to the account.

    Args:
        account_slug (str): Slug of the account to list projects for.
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ListProjectsResponse200]
    """

    kwargs = _get_kwargs(
        account_slug=account_slug,
        per_page=per_page,
        page=page,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    account_slug: str,
    *,
    client: AuthenticatedClient,
    per_page: str | Unset = UNSET,
    page: str | Unset = UNSET,
) -> Error | ListProjectsResponse200 | None:
    """List an account's projects

     List the projects of an account that are visible to the authenticated user, most recently active
    first. Results are paginated. The token must be scoped to the account.

    Args:
        account_slug (str): Slug of the account to list projects for.
        per_page (str | Unset): Number of items per page (max 100)
        page (str | Unset): Page number

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ListProjectsResponse200
    """

    return (
        await asyncio_detailed(
            account_slug=account_slug,
            client=client,
            per_page=per_page,
            page=page,
        )
    ).parsed
