# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.exchange_git_hub_actions_tokenless_token_body import (
    ExchangeGitHubActionsTokenlessTokenBody,
)
from ...models.exchange_git_hub_actions_tokenless_token_response_200 import (
    ExchangeGitHubActionsTokenlessTokenResponse200,
)
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: ExchangeGitHubActionsTokenlessTokenBody | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/auth/github-actions/tokenless/exchange",
    }

    if not isinstance(body, Unset):
        _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | ExchangeGitHubActionsTokenlessTokenResponse200 | None:
    if response.status_code == 200:
        response_200 = ExchangeGitHubActionsTokenlessTokenResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Error.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if response.status_code == 503:
        response_503 = Error.from_dict(response.json())

        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | ExchangeGitHubActionsTokenlessTokenResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: ExchangeGitHubActionsTokenlessTokenBody | Unset = UNSET,
) -> Response[Error | ExchangeGitHubActionsTokenlessTokenResponse200]:
    """Exchange a tokenless GitHub Actions token for an Argos token

     Called by GitHub Actions to exchange a tokenless bearer token for a short-lived Argos project token.
    The provided commit and branch must match the GitHub workflow run.

    Args:
        body (ExchangeGitHubActionsTokenlessTokenBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ExchangeGitHubActionsTokenlessTokenResponse200]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: ExchangeGitHubActionsTokenlessTokenBody | Unset = UNSET,
) -> Error | ExchangeGitHubActionsTokenlessTokenResponse200 | None:
    """Exchange a tokenless GitHub Actions token for an Argos token

     Called by GitHub Actions to exchange a tokenless bearer token for a short-lived Argos project token.
    The provided commit and branch must match the GitHub workflow run.

    Args:
        body (ExchangeGitHubActionsTokenlessTokenBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ExchangeGitHubActionsTokenlessTokenResponse200
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: ExchangeGitHubActionsTokenlessTokenBody | Unset = UNSET,
) -> Response[Error | ExchangeGitHubActionsTokenlessTokenResponse200]:
    """Exchange a tokenless GitHub Actions token for an Argos token

     Called by GitHub Actions to exchange a tokenless bearer token for a short-lived Argos project token.
    The provided commit and branch must match the GitHub workflow run.

    Args:
        body (ExchangeGitHubActionsTokenlessTokenBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ExchangeGitHubActionsTokenlessTokenResponse200]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: ExchangeGitHubActionsTokenlessTokenBody | Unset = UNSET,
) -> Error | ExchangeGitHubActionsTokenlessTokenResponse200 | None:
    """Exchange a tokenless GitHub Actions token for an Argos token

     Called by GitHub Actions to exchange a tokenless bearer token for a short-lived Argos project token.
    The provided commit and branch must match the GitHub workflow run.

    Args:
        body (ExchangeGitHubActionsTokenlessTokenBody | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ExchangeGitHubActionsTokenlessTokenResponse200
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
