# GENERATED BY scripts/regen.py FROM openapi.yaml — DO NOT EDIT BY HAND.
# Any manual change is erased on the next regeneration and will fail the
# `spec-drift` CI job.

import datetime
from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.account_analytics import AccountAnalytics
from ...models.error import Error
from ...models.get_account_analytics_group_by import GetAccountAnalyticsGroupBy
from ...types import UNSET, Response, Unset


def _get_kwargs(
    account_slug: str,
    *,
    from_: datetime.datetime,
    to: datetime.datetime | Unset = UNSET,
    group_by: GetAccountAnalyticsGroupBy,
    project_names: list[str] | str | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    json_from_ = from_.isoformat()
    params["from"] = json_from_

    json_to: str | Unset = UNSET
    if not isinstance(to, Unset):
        json_to = to.isoformat()
    params["to"] = json_to

    json_group_by = group_by.value
    params["groupBy"] = json_group_by

    json_project_names: list[str] | str | Unset
    if isinstance(project_names, Unset):
        json_project_names = UNSET
    elif isinstance(project_names, list):
        json_project_names = project_names

    else:
        json_project_names = project_names
    params["projectNames"] = json_project_names

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/accounts/{account_slug}/analytics".format(
            account_slug=quote(str(account_slug), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> AccountAnalytics | Error | None:
    if response.status_code == 200:
        response_200 = AccountAnalytics.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 500:
        response_500 = Error.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[AccountAnalytics | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    account_slug: str,
    *,
    client: AuthenticatedClient,
    from_: datetime.datetime,
    to: datetime.datetime | Unset = UNSET,
    group_by: GetAccountAnalyticsGroupBy,
    project_names: list[str] | str | Unset = UNSET,
) -> Response[AccountAnalytics | Error]:
    """Get account analytics

     Retrieve build and screenshot metrics for an account. The personal access token must be scoped to
    the account.

    Args:
        account_slug (str): Slug of the account to retrieve analytics for.
        from_ (datetime.datetime): Start of the analytics period, as an ISO 8601 datetime.
        to (datetime.datetime | Unset): End of the analytics period, as an ISO 8601 datetime.
            Defaults to the current time.
        group_by (GetAccountAnalyticsGroupBy): Time period used to group each series data point.
        project_names (list[str] | str | Unset): Optional project name filter. Pass one value or
            repeat the parameter for multiple projects.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AccountAnalytics | Error]
    """

    kwargs = _get_kwargs(
        account_slug=account_slug,
        from_=from_,
        to=to,
        group_by=group_by,
        project_names=project_names,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    account_slug: str,
    *,
    client: AuthenticatedClient,
    from_: datetime.datetime,
    to: datetime.datetime | Unset = UNSET,
    group_by: GetAccountAnalyticsGroupBy,
    project_names: list[str] | str | Unset = UNSET,
) -> AccountAnalytics | Error | None:
    """Get account analytics

     Retrieve build and screenshot metrics for an account. The personal access token must be scoped to
    the account.

    Args:
        account_slug (str): Slug of the account to retrieve analytics for.
        from_ (datetime.datetime): Start of the analytics period, as an ISO 8601 datetime.
        to (datetime.datetime | Unset): End of the analytics period, as an ISO 8601 datetime.
            Defaults to the current time.
        group_by (GetAccountAnalyticsGroupBy): Time period used to group each series data point.
        project_names (list[str] | str | Unset): Optional project name filter. Pass one value or
            repeat the parameter for multiple projects.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AccountAnalytics | Error
    """

    return sync_detailed(
        account_slug=account_slug,
        client=client,
        from_=from_,
        to=to,
        group_by=group_by,
        project_names=project_names,
    ).parsed


async def asyncio_detailed(
    account_slug: str,
    *,
    client: AuthenticatedClient,
    from_: datetime.datetime,
    to: datetime.datetime | Unset = UNSET,
    group_by: GetAccountAnalyticsGroupBy,
    project_names: list[str] | str | Unset = UNSET,
) -> Response[AccountAnalytics | Error]:
    """Get account analytics

     Retrieve build and screenshot metrics for an account. The personal access token must be scoped to
    the account.

    Args:
        account_slug (str): Slug of the account to retrieve analytics for.
        from_ (datetime.datetime): Start of the analytics period, as an ISO 8601 datetime.
        to (datetime.datetime | Unset): End of the analytics period, as an ISO 8601 datetime.
            Defaults to the current time.
        group_by (GetAccountAnalyticsGroupBy): Time period used to group each series data point.
        project_names (list[str] | str | Unset): Optional project name filter. Pass one value or
            repeat the parameter for multiple projects.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AccountAnalytics | Error]
    """

    kwargs = _get_kwargs(
        account_slug=account_slug,
        from_=from_,
        to=to,
        group_by=group_by,
        project_names=project_names,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    account_slug: str,
    *,
    client: AuthenticatedClient,
    from_: datetime.datetime,
    to: datetime.datetime | Unset = UNSET,
    group_by: GetAccountAnalyticsGroupBy,
    project_names: list[str] | str | Unset = UNSET,
) -> AccountAnalytics | Error | None:
    """Get account analytics

     Retrieve build and screenshot metrics for an account. The personal access token must be scoped to
    the account.

    Args:
        account_slug (str): Slug of the account to retrieve analytics for.
        from_ (datetime.datetime): Start of the analytics period, as an ISO 8601 datetime.
        to (datetime.datetime | Unset): End of the analytics period, as an ISO 8601 datetime.
            Defaults to the current time.
        group_by (GetAccountAnalyticsGroupBy): Time period used to group each series data point.
        project_names (list[str] | str | Unset): Optional project name filter. Pass one value or
            repeat the parameter for multiple projects.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AccountAnalytics | Error
    """

    return (
        await asyncio_detailed(
            account_slug=account_slug,
            client=client,
            from_=from_,
            to=to,
            group_by=group_by,
            project_names=project_names,
        )
    ).parsed
